force-app/main/default/objects/Case/fields/Outside_Business_Hours__c.field-meta.xml
<CustomField>
    <fullName>Outside_Business_Hours__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Outside Business Hours</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3 AND 5 AND 6) OR (2 AND 4 AND 5 AND 6)</booleanFilter>
        <errorMessage>There is no active service contract of this customer, please create or choose template contract.</errorMessage>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>ServiceContract.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>ServiceContract.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Template_Contract_RT</value>
        </filterItems>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>ServiceContract.Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>ServiceContract.Type__c</field>
            <operation>equals</operation>
            <value>Bronze Support</value>
        </filterItems>
        <filterItems>
            <field>ServiceContract.StartDate</field>
            <operation>lessOrEqual</operation>
            <valueField>ServiceContract.NOW__c</valueField>
        </filterItems>
        <filterItems>
            <field>ServiceContract.EndDate</field>
            <operation>greaterOrEqual</operation>
            <valueField>ServiceContract.NOW__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Service Contracts</relationshipLabel>
    <relationshipName>Service_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/Business_Hours__c.field-meta.xml
<CustomField>
    <fullName>Business_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Hours</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Service_Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler.cls
public class CaseTriggerHandler {
    public static void populateOutsideBusinessHours(List<Case> cases) {
        Set<Id> serviceContractIds = new Set<Id>();
        for(Case currentCase : cases){
            serviceContractIds.add(currentCase.Service_Contract__c);
        }
        if(!serviceContractIds.isEmpty()){
            Map<Id,ServiceContract> serviceContracts = new Map<Id,ServiceContract>(ServiceContractDAO.getContractByContractIds(serviceContractIds));
            Datetime createdDate = Test.isRunningTest() ? Datetime.newInstance(2020, 04, 14, 4, 30, 0) : System.now();
            for(Case currentCase : cases){
                if(serviceContracts.containsKey(currentCase.Service_Contract__c) && serviceContracts.get(currentCase.Service_Contract__c).Service_Territory__r.Business_Hours__c != null && !BusinessHours.isWithin(serviceContracts.get(currentCase.Service_Contract__c).Service_Territory__r.Business_Hours__c, createdDate )){
                    currentCase.Outside_Business_Hours__c = true;
                }
            }
        }
    }
}