force-app/main/default/objects/Case/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3 AND 5 AND 6) OR (2 AND 4 AND 5 AND 6)</booleanFilter>
        <errorMessage>There is no active service contract of this customer, please create or choose template contract.</errorMessage>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>ServiceContract.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>ServiceContract.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Template_Contract_RT</value>
        </filterItems>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>ServiceContract.Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>ServiceContract.Type__c</field>
            <operation>equals</operation>
            <value>Bronze Support</value>
        </filterItems>
        <filterItems>
            <field>ServiceContract.StartDate</field>
            <operation>lessOrEqual</operation>
            <valueField>ServiceContract.NOW__c</valueField>
        </filterItems>
        <filterItems>
            <field>ServiceContract.EndDate</field>
            <operation>greaterOrEqual</operation>
            <valueField>ServiceContract.NOW__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payroll_Cutoff_Time__mdt/Payroll_Cutoff_Time__mdt.object-meta.xml
<CustomObject>
    <label>Payroll Cutoff Time</label>
    <pluralLabel>Payroll Cutoff Times</pluralLabel>
</CustomObject>

force-app/main/default/objects/Payroll_Cutoff_Time__mdt/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12:00 AM</fullName>
                <default>true</default>
                <label>12:00 AM</label>
            </value>
            <value>
                <fullName>12:30 AM</fullName>
            </value>
            <value>
                <fullName>1:00 AM</fullName>
            </value>
            <value>
                <fullName>1:30 AM</fullName>
            </value>
            <value>
                <fullName>2:00 AM</fullName>
            </value>
            <value>
                <fullName>2:30 AM</fullName>
            </value>
            <value>
                <fullName>3:00 AM</fullName>
            </value>
            <value>
                <fullName>3:30 AM</fullName>
            </value>
            <value>
                <fullName>4:00 AM</fullName>
            </value>
            <value>
                <fullName>4:30 AM</fullName>
            </value>
            <value>
                <fullName>5:00 AM</fullName>
            </value>
            <value>
                <fullName>5:30 AM</fullName>
            </value>
            <value>
                <fullName>6:00 AM</fullName>
            </value>
            <value>
                <fullName>6:30 AM</fullName>
            </value>
            <value>
                <fullName>7:00 AM</fullName>
            </value>
            <value>
                <fullName>7:30 AM</fullName>
            </value>
            <value>
                <fullName>8:00 AM</fullName>
            </value>
            <value>
                <fullName>8:30 AM</fullName>
            </value>
            <value>
                <fullName>9:00 AM</fullName>
            </value>
            <value>
                <fullName>9:30 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:30 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:30 AM</fullName>
            </value>
            <value>
                <fullName>12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:30 PM</fullName>
            </value>
            <value>
                <fullName>1:00 PM</fullName>
            </value>
            <value>
                <fullName>1:30 PM</fullName>
            </value>
            <value>
                <fullName>2:00 PM</fullName>
            </value>
            <value>
                <fullName>2:30 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <formula>TEXT(Product2.Contract_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <formula>TEXT(Product2.Resource_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Service_Time__c.field-meta.xml
<CustomField>
    <fullName>Service_Time__c</fullName>
    <formula>TEXT(Product2.Service_Time__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Usage_per_hour__c.field-meta.xml
<CustomField>
    <fullName>Usage_per_hour__c</fullName>
    <label>Usage per hour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Resource_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Service_Time__c.field-meta.xml
<CustomField>
    <fullName>Service_Time__c</fullName>
    <label>Service Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Hours</fullName>
            </value>
            <value>
                <fullName>Overtime</fullName>
            </value>
            <value>
                <fullName>Night Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>This object will be used to create records for the purpose of invoicing</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Next_Contract_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Contract_Billing_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Next Contract Billing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Night_Time__c.field-meta.xml
<CustomField>
    <fullName>Night_Time__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Night Time</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Service_Contracts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Normal_Time__c.field-meta.xml
<CustomField>
    <fullName>Normal_Time__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Normal Time</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Service_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Number_of_Pre_Purchased_Hours__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Pre_Purchased_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Pre-Purchased Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Overtime__c.field-meta.xml
<CustomField>
    <fullName>Overtime__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Overtime</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Service_Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <label>Project Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Service Contracts</relationshipLabel>
    <relationshipName>Service_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Number_of_Pre_Purchased_Hours__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Pre_Purchased_Hours__c</fullName>
    <formula>ServiceContract.Number_of_Pre_Purchased_Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Pre-Purchased Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Actual_Hours__c.field-meta.xml
<CustomField>
    <fullName>Actual_Hours__c</fullName>
    <label>Actual Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Billable_Hours__c.field-meta.xml
<CustomField>
    <fullName>Billable_Hours__c</fullName>
    <label>Billable Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Usage_per_hour__c.field-meta.xml
<CustomField>
    <fullName>Usage_per_hour__c</fullName>
    <formula>PricebookEntry.Usage_per_hour__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Usage per hour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Contract_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bronze Support</fullName>
    </customValue>
    <customValue>
        <fullName>Silver Support</fullName>
    </customValue>
    <customValue>
        <fullName>Gold Support</fullName>
    </customValue>
    <customValue>
        <fullName>Platinum Support</fullName>
    </customValue>
    <masterLabel>Contract Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Resource_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apprentice</fullName>
    </customValue>
    <customValue>
        <fullName>Design Drafter</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Principal Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Project Administration</fullName>
    </customValue>
    <customValue>
        <fullName>Project Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Senior Design Drafter</fullName>
    </customValue>
    <customValue>
        <fullName>Senior Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Site Supervisor</fullName>
    </customValue>
    <customValue>
        <fullName>Technician</fullName>
    </customValue>
    <customValue>
        <fullName>Senior Project Manager</fullName>
    </customValue>
    <masterLabel>Resource Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WorkOrderLineItemHandlerTest.cls
@isTest
Public class WorkOrderLineItemHandlerTest {

    //@description Create a Service Report and check that an email is sent to the Site Contact with the Service Report 
    static testmethod void transactionCalculationTest1() {
        Test.setMock(HttpCalloutMock.class, new CustomerHttpCalloutMock()); 
        id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Constants.ACC_COMPANY_RT).getRecordTypeId();
 
        List<Account> newAccounts = new List<Account>(); 
        newAccounts = TestDataUtility.createAccounts(1,accRecordTypeId, true);
        
        List<Contact> newContacts = new List<Contact>();
        newContacts = TestDataUtility.createContacts(1,newAccounts[0].id, false);
        newContacts.get(0).Email = 'pq@consulting.com';
        insert newContacts;

        List<OperatingHours> newOPs = new List<OperatingHours>(); 
        newOPs = TestDataUtility.createOperatingHour(1,'SA Operating hours', true);
                
        List<ServiceTerritory> newSTs = new List<ServiceTerritory>(); 
        newSTs = TestDataUtility.createSTerritories(1,'SA',newOPs[0].id , true);
        
        
        List<Product2> newProducts = new List<Product2>(); 
        newProducts = TestDataUtility.createProducts(12 , 'Test', false);
        newProducts[0].Resource_Type__c =  Constants.TYPE_TECHNICIAN;
        newProducts[0].Service_Time__c  =  Constants.SERVICE_BUSINESS;
        newProducts[0].Contract_Type__c =  Constants.TYPE_BRONZE;
        newProducts[1].Resource_Type__c =  Constants.TYPE_TECHNICIAN;
        newProducts[1].Service_Time__c  =  Constants.SERVICE_OVERTIME;   
        newProducts[1].Contract_Type__c =  Constants.TYPE_BRONZE ;
        newProducts[2].Resource_Type__c =  Constants.TYPE_TECHNICIAN;
        newProducts[2].Service_Time__c  =  Constants.SERVICE_NIGHT;   
        newProducts[2].Contract_Type__c =  Constants.TYPE_BRONZE;      
        newProducts[3].Resource_Type__c =  Constants.TYPE_ENGINEER;
        newProducts[3].Service_Time__c  =  Constants.SERVICE_BUSINESS;
        newProducts[3].Contract_Type__c =  Constants.TYPE_BRONZE;
        newProducts[4].Resource_Type__c =  Constants.TYPE_ENGINEER;
        newProducts[4].Service_Time__c  =  Constants.SERVICE_OVERTIME;   
        newProducts[4].Contract_Type__c =  Constants.TYPE_BRONZE ;
        newProducts[5].Resource_Type__c =  Constants.TYPE_ENGINEER;
        newProducts[5].Service_Time__c  =  Constants.SERVICE_NIGHT;   
        newProducts[5].Contract_Type__c =  Constants.TYPE_BRONZE;     
        insert newProducts;   
        
        Pricebook2 pricebook = new Pricebook2 (Name = 'Bronze PB', IsActive = true, Service_Territory__c = newSTs[0].id, Contract_Type__c = Constants.TYPE_BRONZE);
        
        insert pricebook;
        
        Pricebook2 Standardpricebook = new Pricebook2( id = Test.getStandardPricebookId());
        update Standardpricebook ; 
        
        System.AssertNotEquals(NULL, Standardpricebook.id);
        
        List <PricebookEntry> pbEntries = new List <PricebookEntry>();
        Decimal unitPrice = 100;
        
        for(Product2 p :newProducts){        
            PricebookEntry entry = new PricebookEntry (Pricebook2Id = Standardpricebook.id, Product2id = p.id, UnitPrice =unitPrice, IsActive = true, Usage_per_hour__c =1.5 );
            unitPrice = unitPrice +1;
            pbEntries.add(entry);     
        }
        insert pbEntries;   
        
        for(Product2 p :newProducts){        
            PricebookEntry entry = new PricebookEntry (Pricebook2Id = pricebook.id, Product2id = p.id, UnitPrice =unitPrice, IsActive = true, Usage_per_hour__c =1.5 );
            unitPrice = unitPrice +1;
            pbEntries.add(entry);     
        }
        upsert pbEntries;    
        
        BusinessHours normalTimeBH  = BusinessHoursDAO.getBUUsingName('Adelaide Time: 07:30-16:00 Mon-Fri');        
        BusinessHours overtimeBH    = BusinessHoursDAO.getBUUsingName('Adelaide Time: 16:00-00:00 Mon-Fri 7:30-00:00 Sat-Sun'); 
        BusinessHours nighttimeBH   = BusinessHoursDAO.getBUUsingName('Adelaide Time: 00:00-07:30 Mon-Sun'); 
        
        BusinessHours normalTimeBH2 = BusinessHoursDAO.getBUUsingName('Adelaide Time: 06:00-18:00 Mon-Fri');    
        BusinessHours overtimeBH2   = BusinessHoursDAO.getBUUsingName('Adelaide Time: Any time after Business Hours');         
        
        List<ServiceContract> newServiceContracts = new List<ServiceContract>();
        newServiceContracts = TestDataUtility.createServiceContract(1, newAccounts[0].id, newContacts[0].id, newSTs[0].id, false);
        newServiceContracts[0].Normal_Time__c = normalTimeBH.id;
        newServiceContracts[0].Overtime__c = overtimeBH.id;
        newServiceContracts[0].Night_Time__c = nighttimeBH.id;
        newServiceContracts[0].Type__c = Constants.TYPE_BRONZE;
        newServiceContracts[0].Number_of_Pre_Purchased_Hours__c = 0;
        newServiceContracts[0].Type__c = Constants.TYPE_BRONZE;
        newServiceContracts[0].Service_Territory__c = newSTs[0].id;
        newServiceContracts[0].Next_Contract_Billing_Date__c = null;
        newServiceContracts[0].Project_Code__c = 'xyz';
        
        insert newServiceContracts;
        
      //  List<PriceBookEntry> pb = [Select id, Service_Time__c, Resource_Type__c, Contract_Type__c  FROM PricebookEntry Where Pricebook2Id = :pricebook.id];
        
        
     //   System.AssertEquals(NULL, pb);        
         
        List<Case> newCases = new List<Case>();
        newCases = TestDataUtility.createCases(1, newAccounts[0].id, newContacts[0].id, newServiceContracts[0].id, false);
        newCases[0].Service_Territory__c = newSTs[0].id;
        insert newCases;
       
        List<WorkType> newWorkTypes = new List<WorkType>(); 
        newWorkTypes = TestDataUtility.createWorkType(1,'PLC', true);
        
        List<WorkOrder> newWorkOrders = new List<WorkOrder>();
        newWorkOrders = TestDataUtility.createWorkOrders(1, newAccounts[0].id, newContacts[0].id, newCases[0].id, newWorkTypes[0].id, newServiceContracts[0].id, true);
        
        List <ServiceAppointment> generatedSA = [SELECT id FROM ServiceAppointment WHERE ParentRecordId = :newWorkOrders[0].id];
        
        List<User> newUsers = new List<User>(); 
        newUsers = TestDataUtility.createUsers(1, true);      
        
        List<ServiceResource> newSR = new List<ServiceResource>(); 
        newSR = TestDataUtility.createServiceResource(1, newUsers[0].id, true);    
        
        List<Employees__c> newEmployees = new List<Employees__c>(); 
        newEmployees = TestDataUtility.createEmployees(1, Constants.TYPE_ENGINEER, true);   
        
        DateTime start = datetime.newinstance(2019, 12, 31, 12, 0, 0);
        WorkOrderLineItem woli = new WorkOrderLineItem( WorkOrderid = newWorkOrders[0].id,
                                                        Resource__c = newSR[0].id,
                                                        Case__c = newCases[0].id, 
                                                        StartDate = start,
                                                        EndDate = start + 24/16,
                                                        Billable_Hours__c = 16,
                                                        Actual_Hours__c =16,
                                                        Service_Contract__c = newServiceContracts[0].id
                                                        );        
        insert woli;
        
        List <WorkOrderLineItem> wolis = [Select PricebookEntryId, UnitPrice FROM WorkOrderLineItem WHERE WorkOrderId = :newWorkOrders[0].id];
        
        // Check that multiple work order line items have been created for 1 record entered
        System.AssertEquals(wolis.size()>1, true);
        
        // Check that price and quantity have been assigned to the WOLI
         System.AssertNotEquals(wolis[0].PricebookEntryId, NULL);     
         System.AssertNotEquals(wolis[0].UnitPrice, NULL);   
         
        // Check that different pricing has been applied based on Service time
         System.AssertNotEquals(wolis[0].UnitPrice, wolis[1].UnitPrice);   
         
         Test.startTest();
         // Transaction starts at night scenario
        DateTime start2 = datetime.newinstance(2019, 12, 30, 4, 0, 0);
        WorkOrderLineItem woli2 = new WorkOrderLineItem( WorkOrderid = newWorkOrders[0].id,
                                                        Resource__c = newSR[0].id,
                                                        Employee__c = newEmployees[0].id,
                                                        Case__c = newCases[0].id, 
                                                        StartDate = start2,
                                                        EndDate = start2 + 24/16,
                                                        Billable_Hours__c = 16,
                                                        Actual_Hours__c =16,
                                                        Service_Contract__c = newServiceContracts[0].id
                                                        );        
        insert woli2;   
        
        woli2 = [Select PricebookEntryId, EndDate, UnitPrice FROM WorkOrderLineItem WHERE id = :woli2.id Limit 1];
        
        // Check that End date has been updated on inserted record
        System.AssertNotEquals(woli2.EndDate, start2 + 24/16);
        
        // Check that price and quantity have been assigned to the WOLI
         System.AssertNotEquals(woli2.PricebookEntryId, NULL);     
         System.AssertNotEquals(woli2.UnitPrice, NULL);   
        
         // Transaction Ending in Business Holiday scenario
        DateTime start3 = datetime.newinstance(2019, 12, 31, 20, 0, 0);
        
        WorkOrderLineItem woli3 = new WorkOrderLineItem( WorkOrderid = newWorkOrders[0].id,
                                                        Resource__c = newSR[0].id,
                                                        Employee__c = newEmployees[0].id,
                                                        Case__c = newCases[0].id, 
                                                        StartDate = start3,
                                                        EndDate = start3 + 24/16,
                                                        Billable_Hours__c = 16,
                                                        Actual_Hours__c =16,
                                                        Service_Contract__c = newServiceContracts[0].id
                                                        );        
        insert woli3;     
        
        List <WorkOrderLineItem> wolis3 = [Select PricebookEntryId, UnitPrice FROM WorkOrderLineItem WHERE WorkOrderId = :newWorkOrders[0].id];
        
        
         // Transaction Ending in Business Holiday scenario
        DateTime start4 = datetime.newinstance(2020, 1, 1, 20, 0, 0);
        WorkOrderLineItem woli4 = new WorkOrderLineItem( WorkOrderid = newWorkOrders[0].id,
                                                        Resource__c = newSR[0].id,
                                                        Employee__c = newEmployees[0].id,
                                                        Case__c = newCases[0].id, 
                                                        StartDate = start4,
                                                        EndDate = start4 + 24/16,
                                                        Billable_Hours__c = 16,
                                                        Actual_Hours__c =16,
                                                        Service_Contract__c = newServiceContracts[0].id
                                                        );        
        insert woli4;   

        
        woli4 = [Select Id, PricebookEntryId, Quantity, UnitPrice, Description FROM WorkOrderLineItem WHERE id = :woli4.id Limit 1];
        
        // Check that a transaction starting in business hours has the night rate
        System.AssertEquals(woli4.Description.contains('Night'), true);  
        
        // update WOLI scenario
        Sales_Order__c so = new Sales_Order__c(Service_Contract__c = newServiceContracts[0].id, Service_Territory__c = newSTs[0].id, Account__c = newAccounts[0].id, Work_Order__c = newWorkOrders[0].id, Integration_Status__c = Constants.INTEGRATION_STATUS_PENDING);
        insert so;
        
        Sales_Order_Line_Item__c soli = new Sales_Order_Line_Item__c(Sales_Order__c = so.id, Order_Quantity__c = woli4.Quantity, Work_Order_Line_Item__c = woli4.id);
        insert soli;
        
        newWorkOrders[0].Sales_Order__c = so.id;
        update newWorkOrders;
        
        woli4.Quantity = 5;
        woli4.Manual_Override__c = true;
        woli4.Manual_Override_Reason__c = 'test';
        update woli4;
        
        soli = [Select Order_Quantity__c FROM Sales_Order_Line_Item__c WHERE Work_Order_Line_Item__c = :woli4.id Limit 1];
        
        System.AssertEquals(soli.Order_Quantity__c,5);

        Test.stopTest();

        
    }

    static testmethod void transactionCalculationTest2() {
        Test.setMock(HttpCalloutMock.class, new CustomerHttpCalloutMock()); 
        id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Constants.ACC_COMPANY_RT).getRecordTypeId();
 
        List<Account> newAccounts = new List<Account>(); 
        newAccounts = TestDataUtility.createAccounts(1,accRecordTypeId, true);
        
        List<Contact> newContacts = new List<Contact>();
        newContacts = TestDataUtility.createContacts(1,newAccounts[0].id, false);
        newContacts.get(0).Email = 'pq@consulting.com';
        insert newContacts;

        List<OperatingHours> newOPs = new List<OperatingHours>(); 
        newOPs = TestDataUtility.createOperatingHour(1,'SA Operating hours', true);
                
        List<ServiceTerritory> newSTs = new List<ServiceTerritory>(); 
        newSTs = TestDataUtility.createSTerritories(1,'SA',newOPs[0].id , true);
        
        
        List<Product2> newProducts = new List<Product2>(); 
        newProducts = TestDataUtility.createProducts(12 , 'Test', false);
        newProducts[0].Resource_Type__c =  Constants.TYPE_TECHNICIAN;
        newProducts[0].Service_Time__c  =  Constants.SERVICE_BUSINESS;
        newProducts[0].Contract_Type__c =  Constants.TYPE_BRONZE;
        newProducts[1].Resource_Type__c =  Constants.TYPE_TECHNICIAN;
        newProducts[1].Service_Time__c  =  Constants.SERVICE_OVERTIME;   
        newProducts[1].Contract_Type__c =  Constants.TYPE_BRONZE ;
        newProducts[2].Resource_Type__c =  Constants.TYPE_TECHNICIAN;
        newProducts[2].Service_Time__c  =  Constants.SERVICE_NIGHT;   
        newProducts[2].Contract_Type__c =  Constants.TYPE_BRONZE;      
        newProducts[3].Resource_Type__c =  Constants.TYPE_ENGINEER;
        newProducts[3].Service_Time__c  =  Constants.SERVICE_BUSINESS;
        newProducts[3].Contract_Type__c =  Constants.TYPE_BRONZE;
        newProducts[4].Resource_Type__c =  Constants.TYPE_ENGINEER;
        newProducts[4].Service_Time__c  =  Constants.SERVICE_OVERTIME;   
        newProducts[4].Contract_Type__c =  Constants.TYPE_BRONZE ;
        newProducts[5].Resource_Type__c =  Constants.TYPE_ENGINEER;
        newProducts[5].Service_Time__c  =  Constants.SERVICE_NIGHT;   
        newProducts[5].Contract_Type__c =  Constants.TYPE_BRONZE;     
        insert newProducts;   
        
        Pricebook2 pricebook = new Pricebook2 (Name = 'Bronze PB', IsActive = true, Service_Territory__c = newSTs[0].id, Contract_Type__c = Constants.TYPE_BRONZE);
        
        insert pricebook;
        
        Pricebook2 Standardpricebook = new Pricebook2( id = Test.getStandardPricebookId());
        update Standardpricebook ; 
        
        System.AssertNotEquals(NULL, Standardpricebook.id);
        
        List <PricebookEntry> pbEntries = new List <PricebookEntry>();
        Decimal unitPrice = 100;
        
        for(Product2 p :newProducts){        
            PricebookEntry entry = new PricebookEntry (Pricebook2Id = Standardpricebook.id, Product2id = p.id, UnitPrice =unitPrice, IsActive = true, Usage_per_hour__c =1.5 );
            unitPrice = unitPrice +1;
            pbEntries.add(entry);     
        }
        insert pbEntries;   
        
        for(Product2 p :newProducts){        
            PricebookEntry entry = new PricebookEntry (Pricebook2Id = pricebook.id, Product2id = p.id, UnitPrice =unitPrice, IsActive = true, Usage_per_hour__c =1.5 );
            unitPrice = unitPrice +1;
            pbEntries.add(entry);     
        }
        upsert pbEntries;    
        
        BusinessHours normalTimeBH  = BusinessHoursDAO.getBUUsingName('Adelaide Time: 07:30-16:00 Mon-Fri');        
        BusinessHours overtimeBH    = BusinessHoursDAO.getBUUsingName('Adelaide Time: 16:00-00:00 Mon-Fri 7:30-00:00 Sat-Sun'); 
        BusinessHours nighttimeBH   = BusinessHoursDAO.getBUUsingName('Adelaide Time: 00:00-07:30 Mon-Sun'); 
        
        BusinessHours normalTimeBH2 = BusinessHoursDAO.getBUUsingName('Adelaide Time: 06:00-18:00 Mon-Fri');    
        BusinessHours overtimeBH2   = BusinessHoursDAO.getBUUsingName('Adelaide Time: Any time after Business Hours');         
        
        List<ServiceContract> newServiceContracts = new List<ServiceContract>();
        newServiceContracts = TestDataUtility.createServiceContract(1, newAccounts[0].id, newContacts[0].id, newSTs[0].id, false);
        newServiceContracts[0].Normal_Time__c = normalTimeBH.id;
        newServiceContracts[0].Overtime__c = overtimeBH.id;
        newServiceContracts[0].Night_Time__c = nighttimeBH.id;
        newServiceContracts[0].Type__c = Constants.TYPE_BRONZE;
        newServiceContracts[0].Number_of_Pre_Purchased_Hours__c = 0;
        newServiceContracts[0].Type__c = Constants.TYPE_BRONZE;
        newServiceContracts[0].Service_Territory__c = newSTs[0].id;
        newServiceContracts[0].Next_Contract_Billing_Date__c = null;
        
        insert newServiceContracts;
        
        List<Case> newCases = new List<Case>();
        newCases = TestDataUtility.createCases(1, newAccounts[0].id, newContacts[0].id, newServiceContracts[0].id, false);
        newCases[0].Service_Territory__c = newSTs[0].id;
        insert newCases;
       
        List<WorkType> newWorkTypes = new List<WorkType>(); 
        newWorkTypes = TestDataUtility.createWorkType(1,'PLC', true);
        
        List<WorkOrder> newWorkOrders = new List<WorkOrder>();
        newWorkOrders = TestDataUtility.createWorkOrders(1, newAccounts[0].id, newContacts[0].id, newCases[0].id, newWorkTypes[0].id, newServiceContracts[0].id, true);
        
        List <ServiceAppointment> generatedSA = [SELECT id FROM ServiceAppointment WHERE ParentRecordId = :newWorkOrders[0].id];
        
        List<User> newUsers = new List<User>(); 
        newUsers = TestDataUtility.createUsers(1, true);      
        
        List<ServiceResource> newSR = new List<ServiceResource>(); 
        newSR = TestDataUtility.createServiceResource(1, newUsers[0].id, true);    
        
        List<Employees__c> newEmployees = new List<Employees__c>(); 
        newEmployees = TestDataUtility.createEmployees(1, Constants.TYPE_ENGINEER, true);   
        
        DateTime start = datetime.newinstance(2019, 12, 31, 12, 0, 0);
        
        Test.startTest();
        
        // Check logic when only 2 business hours are assigned to a Contract
        newServiceContracts[0].Normal_Time__c = normalTimeBH2.id;
        newServiceContracts[0].Overtime__c = overtimeBH2.id;
        newServiceContracts[0].Night_Time__c = NULL;  
        update newServiceContracts;  
        
        WorkOrderLineItem woli5 = new WorkOrderLineItem( WorkOrderid = newWorkOrders[0].id,
                                                        Resource__c = newSR[0].id,
                                                        Case__c = newCases[0].id, 
                                                        StartDate = start,
                                                        EndDate = start + 24/16,
                                                        Billable_Hours__c = 16,
                                                        Actual_Hours__c =16,
                                                        Service_Contract__c = newServiceContracts[0].id
                                                        );        
        insert woli5;

        // Check logic when only 2 business hours are assigned to a Contract  + Pre purchased Hours update       
        newServiceContracts[0].Number_of_Pre_Purchased_Hours__c = 200;  
        update newServiceContracts;  
        
        newWorkOrders[0].Use_Pre_purchased_Hours__c = 'Yes';
        update newWorkOrders;

        DateTime start5 = datetime.newinstance(2019, 11, 24, 20, 0, 0);
        
        WorkOrderLineItem woli6 = new WorkOrderLineItem( WorkOrderid = newWorkOrders[0].id,
                                                        Resource__c = newSR[0].id,
                                                        Case__c = newCases[0].id, 
                                                        StartDate = start5,
                                                        EndDate = start5 + 24/16,
                                                        Billable_Hours__c = 16,
                                                        Actual_Hours__c =16,
                                                        Quantity = 16,
                                                        Service_Contract__c = newServiceContracts[0].id
                                                        );        
        insert woli6;

        woli6 = [Select Consumed_Pre_Purchased_Hours__c, StartDate, PricebookEntryId , EndDate,  Quantity, Usage_per_hour__c  FROM WorkOrderLineItem WHERE id = :woli6.id Limit 1];
        
        // Check that a consumed hours have been update on transaction so it can be deducted from the work order
        System.AssertEquals(woli6.Consumed_Pre_Purchased_Hours__c, woli6.Quantity* woli6.Usage_per_hour__c); 
        
        // Update Scenario
        Id currentproductId = woli6.PricebookEntryId ;
        DateTime currentStart = woli6.StartDate;
        woli6.StartDate = woli6.StartDate + 0.5;
        woli6.EndDate = woli6.EndDate + 0.5;
        update woli6;
        
        woli6 = [Select  PricebookEntryId, StartDate   FROM WorkOrderLineItem WHERE id = :woli6.id Limit 1];
        // Check that the product has been updated on the WOLI 

        System.AssertNotEquals(woli6.StartDate, currentStart);      
        
        Test.stopTest();   
         
        
    }

    static testmethod void transactionStartDateRules() {
        id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Constants.ACC_COMPANY_RT).getRecordTypeId();
 
        List<Account> newAccounts = new List<Account>(); 
        newAccounts = TestDataUtility.createAccounts(1,accRecordTypeId, true);
        
        List<Contact> newContacts = new List<Contact>();
        newContacts = TestDataUtility.createContacts(1,newAccounts[0].id, false);
        newContacts.get(0).Email = 'pq@consulting.com';
        insert newContacts;

        List<OperatingHours> newOPs = new List<OperatingHours>(); 
        newOPs = TestDataUtility.createOperatingHour(1,'SA Operating hours', true);
                
        List<ServiceTerritory> newSTs = new List<ServiceTerritory>(); 
        newSTs = TestDataUtility.createSTerritories(1,'SA',newOPs[0].id , true);
        
        
        List<Product2> newProducts = new List<Product2>(); 
        newProducts = TestDataUtility.createProducts(12 , 'Test', false);
        newProducts[0].Resource_Type__c =  Constants.TYPE_TECHNICIAN;
        newProducts[0].Service_Time__c  =  Constants.SERVICE_BUSINESS;
        newProducts[0].Contract_Type__c =  Constants.TYPE_BRONZE;
        newProducts[1].Resource_Type__c =  Constants.TYPE_TECHNICIAN;
        newProducts[1].Service_Time__c  =  Constants.SERVICE_OVERTIME;   
        newProducts[1].Contract_Type__c =  Constants.TYPE_BRONZE ;
        newProducts[2].Resource_Type__c =  Constants.TYPE_TECHNICIAN;
        newProducts[2].Service_Time__c  =  Constants.SERVICE_NIGHT;   
        newProducts[2].Contract_Type__c =  Constants.TYPE_BRONZE;      
        newProducts[3].Resource_Type__c =  Constants.TYPE_ENGINEER;
        newProducts[3].Service_Time__c  =  Constants.SERVICE_BUSINESS;
        newProducts[3].Contract_Type__c =  Constants.TYPE_BRONZE;
        newProducts[4].Resource_Type__c =  Constants.TYPE_ENGINEER;
        newProducts[4].Service_Time__c  =  Constants.SERVICE_OVERTIME;   
        newProducts[4].Contract_Type__c =  Constants.TYPE_BRONZE ;
        newProducts[5].Resource_Type__c =  Constants.TYPE_ENGINEER;
        newProducts[5].Service_Time__c  =  Constants.SERVICE_NIGHT;   
        newProducts[5].Contract_Type__c =  Constants.TYPE_BRONZE;     
        insert newProducts;   
        
        Pricebook2 pricebook = new Pricebook2 (Name = 'Bronze PB', IsActive = true, Service_Territory__c = newSTs[0].id, Contract_Type__c = Constants.TYPE_BRONZE);
        
        insert pricebook;
        
        Pricebook2 Standardpricebook = new Pricebook2( id = Test.getStandardPricebookId());
        update Standardpricebook ; 
        
        System.AssertNotEquals(NULL, Standardpricebook.id);
        
        List <PricebookEntry> pbEntries = new List <PricebookEntry>();
        Decimal unitPrice = 100;
        
        for(Product2 p :newProducts){        
            PricebookEntry entry = new PricebookEntry (Pricebook2Id = Standardpricebook.id, Product2id = p.id, UnitPrice =unitPrice, IsActive = true, Usage_per_hour__c =1.5 );
            unitPrice = unitPrice +1;
            pbEntries.add(entry);     
        }
        insert pbEntries;   
        
        for(Product2 p :newProducts){        
            PricebookEntry entry = new PricebookEntry (Pricebook2Id = pricebook.id, Product2id = p.id, UnitPrice =unitPrice, IsActive = true, Usage_per_hour__c =1.5 );
            unitPrice = unitPrice +1;
            pbEntries.add(entry);     
        }
        upsert pbEntries;    
        
        BusinessHours normalTimeBH  = BusinessHoursDAO.getBUUsingName('Adelaide Time: 07:30-16:00 Mon-Fri');        
        BusinessHours overtimeBH    = BusinessHoursDAO.getBUUsingName('Adelaide Time: 16:00-00:00 Mon-Fri 7:30-00:00 Sat-Sun'); 
        BusinessHours nighttimeBH   = BusinessHoursDAO.getBUUsingName('Adelaide Time: 00:00-07:30 Mon-Sun'); 
        
        BusinessHours normalTimeBH2 = BusinessHoursDAO.getBUUsingName('Adelaide Time: 06:00-18:00 Mon-Fri');    
        BusinessHours overtimeBH2   = BusinessHoursDAO.getBUUsingName('Adelaide Time: Any time after Business Hours');         
        
        List<ServiceContract> newServiceContracts = new List<ServiceContract>();
        newServiceContracts = TestDataUtility.createServiceContract(1, newAccounts[0].id, newContacts[0].id, newSTs[0].id, false);
        newServiceContracts[0].Normal_Time__c = normalTimeBH.id;
        newServiceContracts[0].Overtime__c = overtimeBH.id;
        newServiceContracts[0].Night_Time__c = nighttimeBH.id;
        newServiceContracts[0].Type__c = Constants.TYPE_BRONZE;
        newServiceContracts[0].Number_of_Pre_Purchased_Hours__c = 0;
        newServiceContracts[0].Type__c = Constants.TYPE_BRONZE;
        newServiceContracts[0].Service_Territory__c = newSTs[0].id;
        newServiceContracts[0].Next_Contract_Billing_Date__c = null;
        
        insert newServiceContracts;
        
        List<Case> newCases = new List<Case>();
        newCases = TestDataUtility.createCases(1, newAccounts[0].id, newContacts[0].id, newServiceContracts[0].id, false);
        newCases[0].Service_Territory__c = newSTs[0].id;
        insert newCases;
       
        List<WorkType> newWorkTypes = new List<WorkType>(); 
        newWorkTypes = TestDataUtility.createWorkType(1,'PLC', true);
        
        List<WorkOrder> newWorkOrders = new List<WorkOrder>();
        newWorkOrders = TestDataUtility.createWorkOrders(1, newAccounts[0].id, newContacts[0].id, newCases[0].id, newWorkTypes[0].id, newServiceContracts[0].id, true);
        
        List <ServiceAppointment> generatedSA = [SELECT id FROM ServiceAppointment WHERE ParentRecordId = :newWorkOrders[0].id];
        
        List<User> newUsers = new List<User>(); 
        newUsers = TestDataUtility.createUsers(1, true);      
        
        List<ServiceResource> newSR = new List<ServiceResource>(); 
        newSR = TestDataUtility.createServiceResource(1, newUsers[0].id, true);    
        
        List<Employees__c> newEmployees = new List<Employees__c>(); 
        newEmployees = TestDataUtility.createEmployees(1, Constants.TYPE_ENGINEER, true);   
        
        DateTime start = datetime.newinstance(2019, 12, 31, 12, 0, 0);
        Test.startTest();
            WorkOrderLineItem woli = new WorkOrderLineItem( WorkOrderid = newWorkOrders[0].id,
                                                            Resource__c = newSR[0].id,
                                                            Case__c = newCases[0].id, 
                                                            StartDate = start,
                                                            EndDate = start + 24/16,
                                                            Billable_Hours__c = 16,
                                                            Actual_Hours__c =16,
                                                            Service_Contract__c = newServiceContracts[0].id
                                                            ); 
            insert woli;    

            Sales_Order__c sOrder = new Sales_Order__c(Service_Contract__c = newServiceContracts[0].Id);
            insert sOrder;

            Sales_Order_Line_Item__c soli = new Sales_Order_Line_Item__c(Sales_Order__c = sOrder.Id, Work_Order_Line_Item__c = woli.Id);
            insert soli;

            sOrder.Integration_Status__c = Utilities.INTEGRATION_SUCCESSFUL;
            update sOrder;

            Datetime today = Datetime.now();
            woli.StartDate = Datetime.newInstance(today.year(), today.month(), today.day(), 10, 0, 0);
            try{
                update woli;    
            }catch(DmlException ex){
                System.assert(ex.getDmlMessage(0).contains(System.Label.WorkOrderLineItem_StartDate_Update_NotAllowed_CL));
            }
        
        Test.stopTest();
           
         
        
    }

    static testmethod void testPayrolCutoffTime() {
        List<Payroll_Cutoff_Time__mdt> pSettings = [SELECT Id, Day_of_Week__c, Time__c FROM Payroll_Cutoff_Time__mdt limit 1];

        // Assume the current time is 2020/05/04 (Monday) 1.00 PM - test a date before the current time but in the previous week

        Datetime today = Datetime.newInstance(2020, 5, 4, 13, 0, 0);
        Datetime testDate = Datetime.newInstance(2020, 5, 1, 13, 0, 0);
        System.assertEquals(false, Utilities.isOutsidePayrollCutoffTime(testDate, today));

        // Assume the current time is 2020/05/04 (Monday) 1.00 PM - test a date before the current time but in a date before the previous week
        today = Datetime.newInstance(2020, 5, 4, 13, 0, 0);
        testDate = Datetime.newInstance(2020, 4, 1, 13, 0, 0);
        System.assertEquals(true, Utilities.isOutsidePayrollCutoffTime(testDate, today));

        // Assume the current time is 2020/05/04 (Monday) 1.00 PM - test a date after the current time
        today = Datetime.newInstance(2020, 5, 4, 13, 0, 0);
        testDate = Datetime.newInstance(2020, 5, 8, 13, 0, 0);
        System.assertEquals(false, Utilities.isOutsidePayrollCutoffTime(testDate, today));

        // Assume the current time is 2020/05/04 (Monday) 1.00 PM - test a date after the current time
        today = Datetime.newInstance(2020, 5, 4, 13, 0, 0);
        testDate = Datetime.newInstance(2020, 5, 4, 11, 30, 0);
        System.assertEquals(false, Utilities.isOutsidePayrollCutoffTime(testDate, today));

        // Assume the current time is 2020/05/04 (Monday) 6.00 PM - test a date before the current time but in the previous week
        today = Datetime.newInstance(2020, 5, 4, 18, 0, 0);
        testDate = Datetime.newInstance(2020, 5, 1, 13, 0, 0);
        System.assertEquals(true, Utilities.isOutsidePayrollCutoffTime(testDate, today));

        // Assume the current time is 2020/05/04 (Monday) 6.00 PM - test a date before the current time but in a date before the previous week
        today = Datetime.newInstance(2020, 5, 4, 18, 0, 0);
        testDate = Datetime.newInstance(2020, 4, 1, 13, 0, 0);
        System.assertEquals(true, Utilities.isOutsidePayrollCutoffTime(testDate, today));

        // Assume the current time is 2020/05/04 (Monday) 6.00 PM - test a date after the current time
        today = Datetime.newInstance(2020, 5, 4, 18, 0, 0);
        testDate = Datetime.newInstance(2020, 5, 8, 13, 0, 0);
        System.assertEquals(false, Utilities.isOutsidePayrollCutoffTime(testDate, today));

        // Assume the current time is 2020/05/04 (Monday) 6.00 PM - test a date after the current time
        today = Datetime.newInstance(2020, 5, 4, 18, 0, 0);
        testDate = Datetime.newInstance(2020, 5, 4, 18, 30, 0);
        System.assertEquals(false, Utilities.isOutsidePayrollCutoffTime(testDate, today));
        

    }
}