force-app/main/default/objects/Case/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3 AND 5 AND 6) OR (2 AND 4 AND 5 AND 6)</booleanFilter>
        <errorMessage>There is no active service contract of this customer, please create or choose template contract.</errorMessage>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>ServiceContract.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>ServiceContract.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Template_Contract_RT</value>
        </filterItems>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>ServiceContract.Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>ServiceContract.Type__c</field>
            <operation>equals</operation>
            <value>Bronze Support</value>
        </filterItems>
        <filterItems>
            <field>ServiceContract.StartDate</field>
            <operation>lessOrEqual</operation>
            <valueField>ServiceContract.NOW__c</valueField>
        </filterItems>
        <filterItems>
            <field>ServiceContract.EndDate</field>
            <operation>greaterOrEqual</operation>
            <valueField>ServiceContract.NOW__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HTTP_Request__mdt/HTTP_Request__mdt.object-meta.xml
<CustomObject>
    <label>HTTP Request</label>
    <pluralLabel>HTTP Requests</pluralLabel>
</CustomObject>

force-app/main/default/objects/HTTP_Request__mdt/fields/Conflux_River__c.field-meta.xml
<CustomField>
    <fullName>Conflux_River__c</fullName>
    <label>Conflux River</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HTTP_Request__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HTTP_Request__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <description>Please select a value less than 120,000 milliseconds</description>
    <inlineHelpText>Please select a value less than 120,000 milliseconds</inlineHelpText>
    <label>Timeout (ms)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HTTP_Request__mdt/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>This object will be used to create records for the purpose of invoicing</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SyncWithProntoDAO.cls
/**
* 
@author: Cyrille Jeufo - Proquest Consulting
@description: This class handles all data retrieval relative to integrations around Pronto
* 
*/
public class SyncWithProntoDAO {
    
    /**
    * 
    @author: Cyrille Jeufo - Proquest Consulting
    @description: retrieves the HTTP settings to make a callout
    * 
    */
    public static HTTP_Request__mdt getHTTPSettings(String context){
        if(String.isNotBlank(context))
        {
            List<HTTP_Request__mdt> httpSettings = new List<HTTP_Request__mdt>();
            httpSettings = [SELECT Id, URL__c, Method__c, Subscription_Key__c, Version__c, Content_Type__c ,Conflux_River__c, DeveloperName,Timeout__c FROM HTTP_Request__mdt where DeveloperName =: context];
        	if(httpSettings.size() > 0) return httpSettings[0];
        }
        return null;

    }
    
    /**
    * 
    @author: Cyrille Jeufo - Proquest Consulting
    @description: If there is contact on the service contract, use otherwise use contact on the work order is present
    * Update: Instead of getting contact from Service Contract, get it from the Case object 
    */
   	public static String getSalesOrderContact(Sales_Order__c so){
        String contactName;
        List<ServiceContract> contracts = new List<ServiceContract>();
        List<Case> contactFromCase = new List<Case>();
        List<WorkOrder> wos = new List<WorkOrder>();
        List<Contact> contacts = new List<Contact>();
        /* If(so.Service_Contract__c != null){
       
            contracts = [Select Id , ContactId FROM ServiceContract WHERE Id =: so.Service_Contract__c  limit 1];

             if(contracts.size() > 0 ){
                contacts = [Select Id , Name From Contact where Id =: contracts[0].ContactId];
                if(contacts.size() > 0) 
				contactName = contacts[0].Name;
            } 

        } */
        
        If(so.Case__c != null){
            contactFromCase = [Select Id , Contact__c FROM Case WHERE Id =: so.Case__c  limit 1];
            if(contactFromCase.size() > 0 ){  
              contactName = contactFromCase[0].Contact__c;
            }
        }
        
        if(String.isBlank(contactName) && so.Work_Order__c != null){
            wos = [Select Id , ContactId FROM WorkOrder WHERE Id =: so.Work_Order__c  limit 1];
            if(wos.size() > 0){
                contacts = [Select Id , Name From Contact where Id =: wos[0].ContactId limit 1];
                if(contacts.size() > 0) contactName = contacts[0].Name;
            }
        }
        
        return contactName;
    }
    
}