force-app/main/default/objects/Error_log__c/Error_log__c.object-meta.xml
<CustomObject>
    <label>Error Logs</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Integration logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_log__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipName>Integration_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_log__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Error Logs</relationshipLabel>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>This object will be used to create records for the purpose of invoicing</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/Sales_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Indicates what this sales items is about</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Item_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Code__c</fullName>
    <label>Item Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Note</fullName>
            </value>
            <value>
                <fullName>Special (S)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Item_Price__c.field-meta.xml
<CustomField>
    <fullName>Item_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Indicates the price of this item</description>
    <label>Item Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Order_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Order_Quantity__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Order Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <description>Parent Sales Order</description>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <description>Unit of measure</description>
    <label>Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Units</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Contract_Line_Item__c/Service_Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Service Contract Line Item</label>
    <nameField>
        <displayFormat>SCLI-{000000}</displayFormat>
        <label>Service Contract Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Contract_Line_Item__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipName>Service_Contract_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Contract_Line_Item__c/fields/Service_Rate__c.field-meta.xml
<CustomField>
    <fullName>Service_Rate__c</fullName>
    <label>Item_Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Annual_Service_Amount__c.field-meta.xml
<CustomField>
    <fullName>Annual_Service_Amount__c</fullName>
    <label>Annual Service Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Billing_Cycle_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Cycle_Type__c</fullName>
    <label>Billing Cycle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Advance</fullName>
            </value>
            <value>
                <fullName>In Arrears</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Contract_Billing_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Contract_Billing_Cycle__c</fullName>
    <label>Contract Billing Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Next_Contract_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Contract_Billing_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Next Contract Billing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Service Contracts</relationshipLabel>
    <relationshipName>Service_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Units.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EACH</fullName>
        <label>Each</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>PACK OF 10</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
    </customValue>
    <customValue>
        <fullName>1000</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <label>Pack of 200</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>Pack of 25</label>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>500</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
        <label>Bag</label>
    </customValue>
    <customValue>
        <fullName>BOX</fullName>
        <label>1 Box</label>
    </customValue>
    <customValue>
        <fullName>BTLE</fullName>
        <label>Bottle</label>
    </customValue>
    <customValue>
        <fullName>BUCK</fullName>
        <label>Bucket</label>
    </customValue>
    <customValue>
        <fullName>CARD</fullName>
        <label>Card</label>
    </customValue>
    <customValue>
        <fullName>CART</fullName>
        <label>Cartridge</label>
    </customValue>
    <customValue>
        <fullName>COIL</fullName>
        <label>Coil</label>
    </customValue>
    <customValue>
        <fullName>COUT</fullName>
        <label>Callout</label>
    </customValue>
    <customValue>
        <fullName>CTN</fullName>
        <label>Carton</label>
    </customValue>
    <customValue>
        <fullName>DAY</fullName>
        <label>Day</label>
    </customValue>
    <customValue>
        <fullName>DRUM</fullName>
        <label>Drum</label>
    </customValue>
    <customValue>
        <fullName>HOUR</fullName>
        <label>Hour</label>
    </customValue>
    <customValue>
        <fullName>HRS</fullName>
        <label>Hours</label>
    </customValue>
    <customValue>
        <fullName>JAR</fullName>
        <label>Jar</label>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
        <label>Kilogram</label>
    </customValue>
    <customValue>
        <fullName>KIT</fullName>
        <label>Kit</label>
    </customValue>
    <customValue>
        <fullName>KM</fullName>
        <label>Kilometre</label>
    </customValue>
    <customValue>
        <fullName>LEN</fullName>
        <label>Length</label>
    </customValue>
    <customValue>
        <fullName>LOT</fullName>
        <label>Lot</label>
    </customValue>
    <customValue>
        <fullName>LTR</fullName>
        <label>Litre</label>
    </customValue>
    <customValue>
        <fullName>MM</fullName>
        <label>Millimetre</label>
    </customValue>
    <masterLabel>Units</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreateContractFeesBatch.cls
/*******************************************************************************
* @author          Kengo CHINEN (Proquest Consulting)
* @date            4.Dec.2019        
* @description     Sales Order generation for Contract Fees. This class handles creation of Sales Order  + Line Items
                   Errors are stored in Error Log object
• @revision 
• v1.0      - 

*******************************************************************************/

global class CreateContractFeesBatch implements Database.Batchable<sObject>, Database.Stateful {   
    
    // instance member to retain state across transactions
    global Integer recordsProcessed = 0;
    public Set<Id> processedContractIds = new Set<Id>();
    
    private String idParameter;
 
    public CreateContractFeesBATCH(String strParam) {
        idParameter = strParam;
    }
    

    
    // Get Sales Order records with line items that will be processed in the batch
    global Database.QueryLocator start(Database.BatchableContext bc) {

         String query ='';
         // if parameter is a Service Territory
         if(idParameter.startsWith('0Hh'))
             query = 'SELECT ID, Next_Contract_Billing_Date__c, Annual_Service_Amount__c, AccountId, Service_Territory__c, EndDate, Billing_Cycle_Type__c, StartDate,' +
            'Contract_Billing_Cycle__c, (SELECT ID, Description__c, Item_Code__c, Quantity__c,' +
            'Service_Contract__c, Service_Rate__c FROM Service_Contract_Line_Item__r) FROM ServiceContract ' + 
            'WHERE Next_Contract_Billing_Date__c = TODAY ' +
            'AND Service_Territory__c = \'' + idParameter +'\''+
            'LIMIT 50000';
         // if parameter is a Service Contract
         else if(idParameter.startsWith('810')){
             query = 'SELECT ID, Next_Contract_Billing_Date__c, Annual_Service_Amount__c, AccountId, Service_Territory__c, EndDate, Billing_Cycle_Type__c, StartDate,' +
            'Contract_Billing_Cycle__c, (SELECT ID, Description__c, Item_Code__c, Quantity__c,' +
            'Service_Contract__c, Service_Rate__c FROM Service_Contract_Line_Item__r) FROM ServiceContract ' + 
            'WHERE  Id = \'' + idParameter  +'\'';
         }               
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<ServiceContract> serviceContracts){

        // process each batch of records
        List<Sales_Order__c> soToCreate = new List<Sales_Order__c>();
        List<Error_log__c> errorToCreate = new List <Error_log__c>();
        Id contractFeesRTId = Schema.SObjectType.Sales_Order__c.getRecordTypeInfosByDeveloperName().get(Constants.SOR_DEV_ContractFees_RT).getRecordTypeId();
        Id errorContractFeesRTId = Schema.SObjectType.Error_Log__c.getRecordTypeInfosByDeveloperName().get(Constants.ERR_DEV_ContractFees_RT).getRecordTypeId();

        for (ServiceContract sc : serviceContracts) {
            if(!processedContractIds.contains(sc.id)){      
                Sales_Order__c so = new Sales_Order__c(Service_Contract__c = sc.id,
                                                       Account__c = sc.AccountId,
                                                       Service_Territory__c = sc.Service_Territory__c,
                                                       RecordTypeId = contractFeesRTId
                                                       );
                soToCreate.add(so);
                // increment the instance member counter
                recordsProcessed = recordsProcessed + 1;
                processedContractIds.add(sc.id);
            }
        }
        
        Map<Id,String> soGenerationErrorsMap = new Map <Id,String>();
        
        // Insert Sales Orders
        if(soToCreate.size()>0){
            database.saveresult[] soList = database.insert(soToCreate, false);
            
            for(Database.SaveResult sr : soList) {
                for (Integer i = 0; i < soToCreate.size(); i++) {
                    if(!sr.isSuccess()) {
    
                        // Operation failed, so get all errors               
                        for(Database.Error err : sr.getErrors()) {
                        
                            Error_log__c logRecord = new Error_log__c(
                                                         Message__c   = err.getMessage() + ' ' + Label.NewLine.replace('-','') + Label.ContractFees_SOError_CL + err.getFields() , 
                                                         recordTypeId = errorContractFeesRTId , 
                                                         Service_Contract__c = soToCreate[i].Service_Contract__c,
                                                         Status_Code__c = String.valueOf(err.statusCode)
                                                         ); 
                            errorToCreate.add(logRecord);                           
                            soGenerationErrorsMap.put(soToCreate[i].Service_Contract__c, String.valueOf(err.statusCode));
                        }
                    }
                }
            }
        } 
        
        Map <Id,Id> scTosoMap = new Map <Id, Id>(); 
        Map <Id,Id> soToscMap = new Map <Id, Id>(); 
        for(Sales_Order__c so :soToCreate){
            scTosoMap.put(so.Service_Contract__c,so.Id);
            soToscMap.put(so.Id, so.Service_Contract__c);
        }
        
        Map<String, Integer> dividedByMap = new Map<String, Integer>();
        dividedByMap.put(Constants.CYCLE_YEARLY, 1);
        dividedByMap.put(Constants.CYCLE_MONTHLY, 12);
        dividedByMap.put(Constants.CYCLE_QUATERLY, 4);
        dividedByMap.put(Constants.CYCLE_HALFYEARLY, 2);
        
        List<Sales_Order_Line_Item__c> soliToCreate = new List <Sales_Order_Line_Item__c>();
        List<ServiceContract> nextBillingDateUpdate = new List <ServiceContract>();
        for (ServiceContract sc : serviceContracts) {
            if(scTosoMap.get(sc.id)<> NULL){                
                boolean containsLineItem = false;
                
                // Scenario where the contract has a billing cycle
                if(sc.Contract_Billing_Cycle__c <> NULL && sc.Contract_Billing_Cycle__c <> 'None'){
    
                // Calculate Next billing Date based on the cycle            
                Date nextBillingDate;
                if(sc.Billing_Cycle_Type__c == Constants.CYCLE_TYPE_IN_ADVANCE){
                    if(sc.Contract_Billing_Cycle__c == Constants.CYCLE_YEARLY && soGenerationErrorsMap.get(sc.id)==NULL){
                        nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year()+1, sc.Next_Contract_Billing_Date__c.month(), sc.StartDate.day());
                        if(nextBillingDate.day() <> sc.StartDate.day()){
                            nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year(), sc.Next_Contract_Billing_Date__c.month(), sc.StartDate.day()).addYears(1);
                        }

                    }
                    if(sc.Contract_Billing_Cycle__c == Constants.CYCLE_HALFYEARLY && soGenerationErrorsMap.get(sc.id)==NULL){
                        nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year(), sc.Next_Contract_Billing_Date__c.month()+6, sc.StartDate.day());
                        if(nextBillingDate.day() <> sc.StartDate.day()){
                            nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year(), sc.Next_Contract_Billing_Date__c.month(), sc.StartDate.day()).addMonths(6);
                        }
                    }
                    if(sc.Contract_Billing_Cycle__c == Constants.CYCLE_QUATERLY && soGenerationErrorsMap.get(sc.id)==NULL){
                        nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year(), sc.Next_Contract_Billing_Date__c.month()+3, sc.StartDate.day());
                        if(nextBillingDate.day() <> sc.StartDate.day()){
                            nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year(), sc.Next_Contract_Billing_Date__c.month(), sc.StartDate.day()).addMonths(3);
                        }
                    }
                    if(sc.Contract_Billing_Cycle__c == Constants.CYCLE_MONTHLY && soGenerationErrorsMap.get(sc.id)==NULL){
                        nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year(), sc.Next_Contract_Billing_Date__c.month()+1, sc.StartDate.day());
                        if(nextBillingDate.day() <> sc.StartDate.day()){
                            nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year(), sc.Next_Contract_Billing_Date__c.month(), sc.StartDate.day()).addMonths(1);
                        }
                    }
                }
                if(sc.Billing_Cycle_Type__c == Constants.CYCLE_TYPE_IN_ARREARS){
                
                    if(sc.Contract_Billing_Cycle__c == Constants.CYCLE_YEARLY && soGenerationErrorsMap.get(sc.id)==NULL){
                        if(sc.StartDate.day()==1){
                            nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year(), sc.Next_Contract_Billing_Date__c.month(), sc.StartDate.day()).addYears(1).addMonths(1)-1;
                        }   else{
                                nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year()+1, sc.Next_Contract_Billing_Date__c.month(), sc.StartDate.day())-1;
                                if(nextBillingDate.day()<>sc.StartDate.day()-1){
                                    nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year(), sc.Next_Contract_Billing_Date__c.month(), sc.StartDate.day()).addYears(1)-1;
                                }
                            }
                    }
                    if(sc.Contract_Billing_Cycle__c == Constants.CYCLE_HALFYEARLY && soGenerationErrorsMap.get(sc.id)==NULL){
                        if(sc.StartDate.day()==1){
                            nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year(), sc.Next_Contract_Billing_Date__c.month(), sc.StartDate.day()).addMonths(7)-1;
                        }   else{
                                nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year(), sc.Next_Contract_Billing_Date__c.month()+6, sc.StartDate.day())-1;
                                if(nextBillingDate.day()<>sc.StartDate.day()-1){
                                    nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year(), sc.Next_Contract_Billing_Date__c.month(), sc.StartDate.day()).addMonths(6)-1;
                                }
                            }                      
                    }
                    if(sc.Contract_Billing_Cycle__c == Constants.CYCLE_QUATERLY && soGenerationErrorsMap.get(sc.id)==NULL){
                        if(sc.StartDate.day()==1){
                            nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year(), sc.Next_Contract_Billing_Date__c.month(), sc.StartDate.day()).addMonths(4)-1;
                        }   else{
                                nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year(), sc.Next_Contract_Billing_Date__c.month()+3, sc.StartDate.day())-1;
                                if(nextBillingDate.day()<>sc.StartDate.day()-1){
                                    nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year(), sc.Next_Contract_Billing_Date__c.month(), sc.StartDate.day()).addMonths(3)-1;
                                }
                            }                      
                    }
                    if(sc.Contract_Billing_Cycle__c == Constants.CYCLE_MONTHLY && soGenerationErrorsMap.get(sc.id)==NULL){
                        if(sc.StartDate.day()==1){
                            nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year(), sc.Next_Contract_Billing_Date__c.month(), sc.StartDate.day()).addMonths(2)-1;
                        }   else{
                                nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year(), sc.Next_Contract_Billing_Date__c.month()+1, sc.StartDate.day())-1;
                                if(nextBillingDate.day()<>sc.StartDate.day()-1){
                                    nextBillingDate = Date.newInstance(sc.Next_Contract_Billing_Date__c.year(), sc.Next_Contract_Billing_Date__c.month(), sc.StartDate.day()).addMonths(1)-1;
                                }
                        }
                    }
                }
                
                // Update Next billing Date only when the date is still under the contract        
                if(nextBillingDate <= sc.EndDate && soGenerationErrorsMap.get(sc.id)==NULL){
                    sc.Next_Contract_Billing_Date__c = nextBillingDate;
                    nextBillingDateUpdate.add(sc);        
                } else if(soGenerationErrorsMap.get(sc.id)==NULL){
                    // Clear Next Contract Billing Date on Service Contract so no future Sales Order will be created
                    sc.Next_Contract_Billing_Date__c = NULL;
                    nextBillingDateUpdate.add(sc);
                }
                
                
                    // Create Sales Order Line Items based on Service Contract Line Items
                    for (Service_Contract_Line_Item__c scli : sc.Service_Contract_Line_Item__r) {
    
                        Sales_Order_Line_Item__c soli = createSoli(scli);
                        soli.Item_Price__c = soli.Item_Price__c / dividedByMap.get(sc.Contract_Billing_Cycle__c);
                        soli.Sales_Order__c = scTosoMap.get(sc.id);
                        soliToCreate.add(soli);
                        containsLineItem = true;
                    }
    
                    // Create Sales Order Line Item when there is no line item on the contract
                    if(containsLineItem == false){   
                    Sales_Order_Line_Item__c soli = createSoliForContractWithoutLines(sc);
                        soli.Sales_Order__c = scTosoMap.get(sc.id);
                        soli.Item_Price__c = sc.Annual_Service_Amount__c /  dividedByMap.get(sc.Contract_Billing_Cycle__c) ;
                        soliToCreate.add(soli);
                    }
                }
            processedContractIds.add(sc.id);   
            }
        }    
        
        Map<Id,String> soLineInsertErrorsMap = new Map <Id,String>();
        // Insert Sales Orders Line Items
        if(soliToCreate.size()>0){
            database.saveresult[] soliList = database.insert(soliToCreate, false);
            for(Database.SaveResult sr : soliList) {
                for (Integer i = 0; i < soliToCreate.size(); i++) {
                    if(!sr.isSuccess()) {
    
                        // Operation failed, so get all errors               
                        for(Database.Error err : sr.getErrors()) {
                        
                            Error_log__c logRecord = new Error_log__c(
                                                         Message__c   = err.getMessage() +  ' ' + Label.NewLine.replace('-','')+ Label.ContractFees_SOLIError_CL + err.getFields() , 
                                                         recordTypeId = errorContractFeesRTId , 
                                                         Service_Contract__c = soToscMap.get(soliToCreate[i].Sales_Order__c),
                                                         Status_Code__c = String.valueOf(err.statusCode)
                                                         ); 
                            errorToCreate.add(logRecord);
                            soLineInsertErrorsMap.put(soToscMap.get(soliToCreate[i].Sales_Order__c), String.valueOf(err.statusCode));
                        }
                    }
                }
            }
        } 
        // delete created Sales Order for which the line item had an issue and could not be generated
        // remove from contract to be updated with the next billing date the one with a line item issue
        List<Sales_Order__c> deleteSalesOrder = new List <Sales_Order__c>();
        List<ServiceContract> contractUpdateList = new List <ServiceContract>();

        for(Sales_Order__c so :soToCreate){
            if(soLineInsertErrorsMap.get(so.Service_Contract__c)<> NULL){
                deleteSalesOrder.add(so);
            }
        }
        for(ServiceContract sc :nextBillingDateUpdate){
            if(soLineInsertErrorsMap.get(sc.id)== NULL){
                contractUpdateList.add(sc);
            }
        }
        
        
        if(deleteSalesOrder.size()>0){
            delete deleteSalesOrder;
        }
        
  
        // Update Service Contract Next billing Date
        if(contractUpdateList.size()>0){
            database.saveresult[] scList = database.update(contractUpdateList, false);
            
            for(Database.SaveResult sr : scList) {
                for (Integer i = 0; i < scList.size(); i++) {
                    if(!sr.isSuccess()) {                   
                        // Operation failed, so get all errors               
                        for(Database.Error err : sr.getErrors()) {      
                            Error_log__c logRecord = new Error_log__c(
                                                         Message__c   = err.getMessage() + ' ' + Label.NewLine.replace('-','') +Label.ContractFees_NextBillingDateError_CL + err.getFields() , 
                                                         recordTypeId = errorContractFeesRTId , 
                                                         Service_Contract__c = contractUpdateList[i].Id,
                                                         Status_Code__c = String.valueOf(err.statusCode)
                                                         ); 
                            errorToCreate.add(logRecord);
                        }
                    }
                }
            }
        } 
        if(errorToCreate.size()>0){
            insert errorToCreate;
        }
        
    }    
    global void finish(Database.BatchableContext bc){
        System.debug(recordsProcessed + '**records processed**');
    }  
    
    public static Sales_Order_Line_Item__c createSoli(Service_Contract_Line_Item__c scli) {    
        Sales_Order_Line_Item__c soli = new Sales_Order_Line_Item__c(
                                            Order_Quantity__c = scli.Quantity__c,
                                            Description__c = Label.ContractFees_LineDescription_CL + ' ' + scli.Item_Code__c,
                                            Item_Code__c = 'Special (S)' ,
                                            Units__c = Constants.UNITS_EACH,
                                            Item_Price__c = scli.Service_Rate__c  
                                        );
        return soli;
    } 
    public static Sales_Order_Line_Item__c createSoliForContractWithoutLines(ServiceContract sc) {    
        Sales_Order_Line_Item__c soli = new Sales_Order_Line_Item__c(
                                            
                                            Order_Quantity__c = 1,
                                            Description__c = Label.ContractFees_LineDescription_CL ,
                                            Item_Code__c = 'Special (S)' ,
                                            Units__c = Constants.UNITS_EACH,
                                            Item_Price__c = sc.Annual_Service_Amount__c
                                        );
        return soli; 
    }   
}