force-app/main/default/objects/FSL__User_Territory__c/FSL__User_Territory__c.object-meta.xml
<CustomObject>
    <description>Which Territories are visible to this user (Default = All)</description>
    <label>User Territory</label>
    <nameField>
        <displayFormat>ULID-{000000}</displayFormat>
        <label>User Territory Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Territories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceTerritoryMember/fields/User_Territory__c.field-meta.xml
<CustomField>
    <fullName>User_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Territory</label>
    <referenceTo>FSL__User_Territory__c</referenceTo>
    <relationshipLabel>Service Territory Members</relationshipLabel>
    <relationshipName>Service_Territory_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CleanupUserTerritoryBatchJob.cls
/**
* 
@author: Imalka Fernando - Proquest Consulting
@description: This class retrieves all records matching a query passed from CleanupUserTerritoryScheduleJob and
			  those records will be deleted from the system
* 
*/
global class CleanupUserTerritoryBatchJob implements Database.Batchable<sObject> , Database.AllowsCallouts, Database.Stateful{
    global final String query;

    public CleanupUserTerritoryBatchJob(String queryIn) {
        query = queryIn;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, 
                        List<sObject> scope){

        if(scope != null){
            for(SObject sobj : scope){
                ServiceTerritoryMember stm = (ServiceTerritoryMember)sobj;
                FSL__User_Territory__c utToDelete = new FSL__User_Territory__c(Id = stm.User_Territory__c);
                DeleteUserTerritory syncjob = new DeleteUserTerritory(utToDelete);
                ID jobID = System.enqueueJob(syncjob);
            }
        }
    }

    global void finish(Database.BatchableContext BC){
        
    }
}