force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>This object will be used to create records for the purpose of invoicing</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/Sales_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <description>Parent Sales Order</description>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Aggregate_Billing_Format__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Billing_Format__c</fullName>
    <label>Aggregate Billing Format</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Total_Billable_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Billable_Hours__c</fullName>
    <label>Total Billable Hours</label>
    <summarizedField>WorkOrderLineItem.Billable_Hours__c</summarizedField>
    <summaryForeignKey>WorkOrderLineItem.WorkOrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/SalesOrderLineItemTriggerHandler.cls
public class SalesOrderLineItemTriggerHandler {

    public static void populateDescription(List<Sales_Order_Line_Item__c> newSalesOrderLines){
        Set<Id> salesOrderIds = new Set<Id>();
        Set<Id> workOrderIds = new Set<Id>();
        for(Sales_Order_Line_Item__c soli : newSalesOrderLines){
            if(soli.Work_Order__c != null ){
                salesOrderIds.add(soli.Sales_Order__c);
                workOrderIds.add(soli.Work_Order__c);
            }
        }

        if(!salesOrderIds.isEmpty()){
            Map<Id,Sales_Order__c> salesOrders = new Map<Id,Sales_Order__c>(SalesOrderDAO.getSalesOrdersForBillingTerm(salesOrderIds, Constants.CYCLE_AGGREGATE));
            Map<Id,WorkOrder> workOrders = new Map<Id,WorkOrder>(WorkOrderDAO.getWorkOrdersUsingIds(workOrderIds));
            for(Sales_Order_Line_Item__c soli : newSalesOrderLines){
                Sales_Order__c sOrder = salesOrders.get(soli.Sales_Order__c);
                if(soli.Work_Order__c != null && sOrder.Service_Contract__r.Aggregate_Billing_Format__c != ''){
                    soli.Notes__c = getSOLIDescription(sOrder.Service_Contract__r.Aggregate_Billing_Format__c, workOrders.get(soli.Work_Order__c));
                }
            }
        }
    }

    private static String getSOLIDescription(String format, WorkOrder wOrder){
        String description = '';
        if(format != null && format != ''){
            //Total_Billable_Hours__c:Hours,WorkOrderNumber:Salesforce Work Order No,
            for(String fSplit : format.split(',')){
                List<String> lSplits = fSplit.split(':');
                description += (lSplits.size() > 1 ? (lSplits.get(1) + ' - ') : '')  + (wOrder.get(lSplits.get(0)) != null ? wOrder.get(lSplits.get(0)) : '')+'<br/>';
            }
        }
        return description;
    }
}