force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>This object will be used to create records for the purpose of invoicing</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Aggregate_Billing_Format__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Billing_Format__c</fullName>
    <label>Aggregate Billing Format</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Billing_Terms__c.field-meta.xml
<CustomField>
    <fullName>Billing_Terms__c</fullName>
    <label>Billing Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Aggregated Billing</fullName>
            </value>
            <value>
                <fullName>Individual Work Orders</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
                <isActive>false</isActive>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>Yearly</fullName>
                <isActive>false</isActive>
                <label>Yearly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SalesOrderDAO.cls
public class SalesOrderDAO {
    public static  List<Sales_Order__c> getSalesOrdersForBillingTerm(Set<Id> soIds, String billingTerm){
        List<Sales_Order__c> salesOrders = [SELECT  id, 
                                                    Service_Contract__c,
                                                    Service_Contract__r.Aggregate_Billing_Format__c,
                                                    Service_Contract__r.Billing_Terms__c
                                            FROM    Sales_Order__c 
                                            WHERE   Id IN :soIds
                                            AND     Service_Contract__r.Billing_Terms__c = :billingTerm];

        return salesOrders;
        
    }
}