force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>This object will be used to create records for the purpose of invoicing</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line_Item__c/Sales_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <description>Parent Sales Order</description>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Work_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order Line Item</label>
    <referenceTo>WorkOrderLineItem</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesOrderLineItemDAO.cls
public class SalesOrderLineItemDAO {
    public static  List<Sales_Order_Line_Item__c> getSalesOrdersLinesForWOLI(Set<Id> woliIds){
        List<Sales_Order_Line_Item__c> salesOrderLines = [  SELECT  id, 
                                                                    Work_Order_Line_Item__c
                                                            FROM    Sales_Order_Line_Item__c 
                                                            WHERE   Work_Order_Line_Item__c IN :woliIds
                                                            AND     Sales_Order__r.Integration_Status__c = :Utilities.INTEGRATION_SUCCESSFUL];

        return salesOrderLines;
        
    }

    public static  List<Sales_Order_Line_Item__c> getSOLinesForWOLI(Set<Id> woliIds){
        List<Sales_Order_Line_Item__c> salesOrderLines = [  SELECT  id, 
                                                                    Work_Order_Line_Item__c,
                                                                    Sales_Order__c
                                                            FROM    Sales_Order_Line_Item__c 
                                                            WHERE   Work_Order_Line_Item__c IN :woliIds];

        return salesOrderLines;
        
    }
}