force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>This object will be used to create records for the purpose of invoicing</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Action_Taken__c.field-meta.xml
<CustomField>
    <fullName>Action_Taken__c</fullName>
    <label>Action Taken</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_No__c</fullName>
    <formula>Account__r.Account_Code_Formula__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field shows account&#39;s &quot;Account Code&quot; information</inlineHelpText>
    <label>Customer No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Customer_Reference__c.field-meta.xml
<CustomField>
    <fullName>Customer_Reference__c</fullName>
    <label>Customer Reference</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Initial_Findings__c.field-meta.xml
<CustomField>
    <fullName>Initial_Findings__c</fullName>
    <label>Initial Findings</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Reported_Fault__c.field-meta.xml
<CustomField>
    <fullName>Reported_Fault__c</fullName>
    <label>Reported Fault</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/SC_Project_Code__c.field-meta.xml
<CustomField>
    <fullName>SC_Project_Code__c</fullName>
    <label>Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <formula>IF( Account__r.RecordType.DeveloperName = &#39;Cash_Account_RT&#39;,
 Account__r.BillingStreet  + &quot; &quot;+ Account__r.BillingCity + &quot; &quot; +  Account__r.BillingPostalCode +  &quot; &quot; + Account__r.BillingState,
Service_Contract__r.ShippingStreet + &quot; &quot;+ Service_Contract__r.ShippingCity + &quot; &quot; +  Service_Contract__r.ShippingPostalCode +  &quot; &quot; + Service_Contract__r.ShippingState )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field shows service contract&#39;s address information</inlineHelpText>
    <label>Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Suggested_Follow_up__c.field-meta.xml
<CustomField>
    <fullName>Suggested_Follow_up__c</fullName>
    <label>Suggested Follow-up</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/TECH_Company_Code__c.field-meta.xml
<CustomField>
    <fullName>TECH_Company_Code__c</fullName>
    <description>Holds company code for integration purposes</description>
    <formula>Service_Territory__r.Branch_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/TECH_Work_Order_Territory_Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>TECH_Work_Order_Territory_Branch_Code__c</fullName>
    <formula>Service_Territory__r.Branch_Code__c</formula>
    <label>Work Order Territory Branch Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/Sales_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Indicates what this sales items is about</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Item_Price__c.field-meta.xml
<CustomField>
    <fullName>Item_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Indicates the price of this item</description>
    <label>Item Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Order_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Order_Quantity__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Order Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <description>Parent Sales Order</description>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <defaultValue>10.0</defaultValue>
    <label>Tax Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Technician__c.field-meta.xml
<CustomField>
    <fullName>Technician__c</fullName>
    <formula>IF(ISBLANK(Work_Order_Line_Item__c), &#39;&#39;, Work_Order_Line_Item__r.Resource_Formula__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field shows related Work Order Line Item Resource field for labour line</inlineHelpText>
    <label>Technician</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <description>Unit of measure</description>
    <label>Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Units</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Work_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order Line Item</label>
    <referenceTo>WorkOrderLineItem</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Action_Taken__c.field-meta.xml
<CustomField>
    <fullName>Action_Taken__c</fullName>
    <label>Action Taken</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Initial_Findings__c.field-meta.xml
<CustomField>
    <fullName>Initial_Findings__c</fullName>
    <label>Initial Findings</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Suggested_Follow_up__c.field-meta.xml
<CustomField>
    <fullName>Suggested_Follow_up__c</fullName>
    <label>Suggested Follow-up</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/SC_Project_Code__c.field-meta.xml
<CustomField>
    <fullName>SC_Project_Code__c</fullName>
    <label>Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/TECH_Work_Order_Territory_Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>TECH_Work_Order_Territory_Branch_Code__c</fullName>
    <formula>ServiceTerritory.Branch_Code__c</formula>
    <label>Work Order Territory Branch Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <label>Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Units</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Units.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EACH</fullName>
        <label>Each</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>PACK OF 10</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
    </customValue>
    <customValue>
        <fullName>1000</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <label>Pack of 200</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>Pack of 25</label>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>500</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
        <label>Bag</label>
    </customValue>
    <customValue>
        <fullName>BOX</fullName>
        <label>1 Box</label>
    </customValue>
    <customValue>
        <fullName>BTLE</fullName>
        <label>Bottle</label>
    </customValue>
    <customValue>
        <fullName>BUCK</fullName>
        <label>Bucket</label>
    </customValue>
    <customValue>
        <fullName>CARD</fullName>
        <label>Card</label>
    </customValue>
    <customValue>
        <fullName>CART</fullName>
        <label>Cartridge</label>
    </customValue>
    <customValue>
        <fullName>COIL</fullName>
        <label>Coil</label>
    </customValue>
    <customValue>
        <fullName>COUT</fullName>
        <label>Callout</label>
    </customValue>
    <customValue>
        <fullName>CTN</fullName>
        <label>Carton</label>
    </customValue>
    <customValue>
        <fullName>DAY</fullName>
        <label>Day</label>
    </customValue>
    <customValue>
        <fullName>DRUM</fullName>
        <label>Drum</label>
    </customValue>
    <customValue>
        <fullName>HOUR</fullName>
        <label>Hour</label>
    </customValue>
    <customValue>
        <fullName>HRS</fullName>
        <label>Hours</label>
    </customValue>
    <customValue>
        <fullName>JAR</fullName>
        <label>Jar</label>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
        <label>Kilogram</label>
    </customValue>
    <customValue>
        <fullName>KIT</fullName>
        <label>Kit</label>
    </customValue>
    <customValue>
        <fullName>KM</fullName>
        <label>Kilometre</label>
    </customValue>
    <customValue>
        <fullName>LEN</fullName>
        <label>Length</label>
    </customValue>
    <customValue>
        <fullName>LOT</fullName>
        <label>Lot</label>
    </customValue>
    <customValue>
        <fullName>LTR</fullName>
        <label>Litre</label>
    </customValue>
    <customValue>
        <fullName>MM</fullName>
        <label>Millimetre</label>
    </customValue>
    <masterLabel>Units</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SalesOrder.cls
/**
* 
@author: Cyrille Jeufo - Proquest Consulting
@description: classes wrapping sales order and Sales Order line items
* 
*/
public class SalesOrder {

    public String id {get;set;} 
    public String account_code {get;set;} 
    public String action_taken {get;set;} 
    public String caseNumber {get;set;} // in json: case
    public String company {get;set;} 
    public String territory_company {get; set;}
    public String contact_name {get;set;} 
    public String customer_ref {get;set;} 
    public String initial_findings {get;set;} 
    public String order_date {get;set;} 
    public String project_code {get;set;} 
    public String reported_fault {get;set;} 
    public List<SalesOrderItems> sales_order_items {get;set;} 
    public String site {get;set;} 
    public String suggested_followup {get;set;} 
    public String work_order {get;set;} 
    public Long timestamp {get;set;} 
    
    public class SalesOrderItems {
        public String id {get;set;} 
        public String description {get;set;} 
        public String notes {get;set;} 
        public String measure {get;set;} 
        public Double price {get;set;} 
        public Double price_per_measure {get;set;} 
        public Double qty {get;set;} 
        public Double tax_rate {get;set;} 
        public String technician {get;set;} 
        public String work_order {get;set;} 
    }
    
    public static SalesOrder WrappedSO(Sales_Order__c soIn){
        SalesOrder soWrapped = new SalesOrder();
        
        soWrapped.id = soIn.Id;
        soWrapped.account_code = soIn.Customer_No__c;
        soWrapped.action_taken = soIn.Action_Taken__c;
        soWrapped.caseNumber = soIn.Case_Number__c;
        soWrapped.company = soIn.TECH_Company_Code__c;
        soWrapped.territory_company = soIn.TECH_Work_Order_Territory_Branch_Code__c;
        soWrapped.customer_ref = soIn.Customer_Reference__c;
        soWrapped.initial_findings = soIn.Initial_Findings__c;
        //date format: year/month/day
        soWrapped.order_date = (soIn.Order_Date__c != null ? string.valueOf(date.newinstance(soIn.Order_Date__c.year(), soIn.Order_Date__c.month(), soIn.Order_Date__c.day())) : null );
        soWrapped.project_code = soIn.SC_Project_Code__c ;
        soWrapped.reported_fault = soIn.Reported_Fault__c;
        soWrapped.site = soIn.Site__c;
        soWrapped.suggested_followup = soIn.Suggested_Follow_up__c;
        soWrapped.work_order = (soIn.Work_Order__c != null ? [SELECT WorkOrderNumber FROM WorkOrder WHERE ID =: soIn.Work_Order__c ].WorkOrderNumber : null);
        if(soIn.LastModifiedDate != null){
            soWrapped.timestamp = soIn.LastModifiedDate.getTime();
        }
        
        if(soIn.createdDate != null){
            soWrapped.timestamp = soIn.createdDate.getTime();
        }
        
        if(soWrapped.timestamp == null)
        {
            soWrapped.timestamp = System.now().getTime();
        }
        return soWrapped;
    }
    
    public static SalesOrderItems WrappedSOLI(Sales_Order_Line_Item__c soliIn){
        SalesOrderItems soliWrapped = new SalesOrderItems();
        
        soliWrapped.id = soliIn.Id;
        soliWrapped.description = soliIn.Description__c;
        soliWrapped.notes = soliIn.Notes__c != null ? soliIn.Notes__c.replaceAll('<br>','\r\n') : '';
        soliWrapped.measure = soliIn.Units__c;
        soliWrapped.price = soliIn.Item_Price__c.setScale(2);
        soliWrapped.qty = soliIn.Order_Quantity__c;
        soliWrapped.work_order = (soliIn.Work_Order_Line_Item__c != null ? [SELECT Id, LineItemNumber FROM WorkOrderLineItem WHERE ID =: soliIn.Work_Order_Line_Item__c ].LineItemNumber : null);
        soliWrapped.technician = soliIn.Technician__c;
        soliWrapped.tax_rate = soliIn.Tax_Rate__c != null ? soliIn.Tax_Rate__c : 10.0;

        return soliWrapped;
    }
}