force-app/main/default/objects/Pricebook2/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <formula>TEXT(Product2.Contract_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <formula>TEXT(Product2.Resource_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Service_Time__c.field-meta.xml
<CustomField>
    <fullName>Service_Time__c</fullName>
    <formula>TEXT(Product2.Service_Time__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Usage_per_hour__c.field-meta.xml
<CustomField>
    <fullName>Usage_per_hour__c</fullName>
    <label>Usage per hour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Resource_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Service_Time__c.field-meta.xml
<CustomField>
    <fullName>Service_Time__c</fullName>
    <label>Service Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Hours</fullName>
            </value>
            <value>
                <fullName>Overtime</fullName>
            </value>
            <value>
                <fullName>Night Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Next_Contract_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Contract_Billing_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Next Contract Billing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Service Contracts</relationshipLabel>
    <relationshipName>Service_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Contract_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bronze Support</fullName>
    </customValue>
    <customValue>
        <fullName>Silver Support</fullName>
    </customValue>
    <customValue>
        <fullName>Gold Support</fullName>
    </customValue>
    <customValue>
        <fullName>Platinum Support</fullName>
    </customValue>
    <masterLabel>Contract Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Resource_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apprentice</fullName>
    </customValue>
    <customValue>
        <fullName>Design Drafter</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Principal Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Project Administration</fullName>
    </customValue>
    <customValue>
        <fullName>Project Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Senior Design Drafter</fullName>
    </customValue>
    <customValue>
        <fullName>Senior Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Site Supervisor</fullName>
    </customValue>
    <customValue>
        <fullName>Technician</fullName>
    </customValue>
    <customValue>
        <fullName>Senior Project Manager</fullName>
    </customValue>
    <masterLabel>Resource Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ServiceReportTriggerHandlerTest.cls
@isTest

Public class ServiceReportTriggerHandlerTest {

    //@description Create a Service Report and check that an email is sent to the Site Contact with the Service Report 
    public static testMethod void srAutomaticEmailTest() {

        id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Company').getRecordTypeId();
 
        List<Account> newAccounts = new List<Account>(); 
        newAccounts = TestDataUtility.createAccounts(1,accRecordTypeId, true);
        
        List<Contact> newContacts = new List<Contact>();
        newContacts = TestDataUtility.createContacts(1,newAccounts[0].id, false);
        newContacts.get(0).Email = 'pq@consulting.com';
        insert newContacts;

        List<OperatingHours> newOPs = new List<OperatingHours>(); 
        newOPs = TestDataUtility.createOperatingHour(1,'SA Operating hours', true);
                
        List<ServiceTerritory> newSTs = new List<ServiceTerritory>(); 
        newSTs = TestDataUtility.createSTerritories(1,'SA',newOPs[0].id , true);

        List<Product2> newProducts = new List<Product2>(); 
        newProducts = TestDataUtility.createProducts(12 , 'Test', false);
        newProducts[0].Resource_Type__c =  Constants.TYPE_TECHNICIAN;
        newProducts[0].Service_Time__c  =  Constants.SERVICE_BUSINESS;
        newProducts[0].Contract_Type__c =  Constants.TYPE_BRONZE;
        newProducts[1].Resource_Type__c =  Constants.TYPE_TECHNICIAN;
        newProducts[1].Service_Time__c  =  Constants.SERVICE_OVERTIME;   
        newProducts[1].Contract_Type__c =  Constants.TYPE_BRONZE ;
        newProducts[2].Resource_Type__c =  Constants.TYPE_TECHNICIAN;
        newProducts[2].Service_Time__c  =  Constants.SERVICE_NIGHT;   
        newProducts[2].Contract_Type__c =  Constants.TYPE_BRONZE;      
        newProducts[3].Resource_Type__c =  Constants.TYPE_ENGINEER;
        newProducts[3].Service_Time__c  =  Constants.SERVICE_BUSINESS;
        newProducts[3].Contract_Type__c =  Constants.TYPE_BRONZE;
        newProducts[4].Resource_Type__c =  Constants.TYPE_ENGINEER;
        newProducts[4].Service_Time__c  =  Constants.SERVICE_OVERTIME;   
        newProducts[4].Contract_Type__c =  Constants.TYPE_BRONZE ;
        newProducts[5].Resource_Type__c =  Constants.TYPE_ENGINEER;
        newProducts[5].Service_Time__c  =  Constants.SERVICE_NIGHT;   
        newProducts[5].Contract_Type__c =  Constants.TYPE_BRONZE;     
        insert newProducts;   
        
        Pricebook2 pricebook = new Pricebook2 (Name = 'Bronze PB', IsActive = true, Service_Territory__c = newSTs[0].id, Contract_Type__c = Constants.TYPE_BRONZE);
        
        insert pricebook;
        
        Pricebook2 Standardpricebook = new Pricebook2( id = Test.getStandardPricebookId());
        update Standardpricebook ; 
        
        System.AssertNotEquals(NULL, Standardpricebook.id);
        
        List <PricebookEntry> pbEntries = new List <PricebookEntry>();
        Decimal unitPrice = 100;
        
        for(Product2 p :newProducts){        
            PricebookEntry entry = new PricebookEntry (Pricebook2Id = Standardpricebook.id, Product2id = p.id, UnitPrice =unitPrice, IsActive = true, Usage_per_hour__c =1.5 );
            unitPrice = unitPrice +1;
            pbEntries.add(entry);     
        }
        insert pbEntries;   
        
        for(Product2 p :newProducts){        
            PricebookEntry entry = new PricebookEntry (Pricebook2Id = pricebook.id, Product2id = p.id, UnitPrice =unitPrice, IsActive = true, Usage_per_hour__c =1.5 );
            unitPrice = unitPrice +1;
            pbEntries.add(entry);     
        }
        upsert pbEntries; 

        List<ServiceContract> newServiceContracts = new List<ServiceContract>();
        newServiceContracts = TestDataUtility.createServiceContract(1, newAccounts[0].id, newContacts[0].id, newSTs[0].id, false);     
        newServiceContracts[0].Type__c = Constants.TYPE_BRONZE;
        newServiceContracts[0].Service_Territory__c = newSTs[0].id;
        newServiceContracts[0].Next_Contract_Billing_Date__c = null;
        
        insert newServiceContracts;
                    
         
        List<Case> newCases = new List<Case>();
        newCases = TestDataUtility.createCases(1, newAccounts[0].id, newContacts[0].id, newServiceContracts[0].id, true);
       
        List<WorkType> newWorkTypes = new List<WorkType>(); 
        newWorkTypes = TestDataUtility.createWorkType(1,'PLC', true);
        
        List<WorkOrder> newWorkOrders = new List<WorkOrder>();
        newWorkOrders = TestDataUtility.createWorkOrders(1, newAccounts[0].id, newContacts[0].id, newCases[0].id, newWorkTypes[0].id, newServiceContracts[0].id, true);
        
        List <ServiceAppointment> generatedSA = [SELECT id FROM ServiceAppointment WHERE ParentRecordId = :newWorkOrders[0].id];
        
        List<ContentVersion> newContentVersions = new List<ContentVersion>(); 
        newContentVersions = TestDataUtility.createContentVersion(1,'Service Report', true);        
        
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument]; 
               
        List <ContentDocumentLink> newContentDocumentLink = new List <ContentDocumentLink>();
        newContentDocumentLink = TestDataUtility.createContentDocumentLink(1, generatedSA[0].id, documents[0].id, true );
       
        ServiceReport sr = new ServiceReport();
        //sr.ContentVersionDocumentId = documents[0].id ;
        sr.DocumentBody = Blob.valueOf('Test Content') ; 
        sr.DocumentContentType ='application/pdf';
        sr.DocumentName='Test';
        sr.ParentId = generatedSA[0].id ; 
        insert sr ; 
        
        // newContentVersions
        
        List <ContentDocumentLink> cdl = [Select id FROM ContentDocumentLink WHERE ContentDocumentId = :documents[0].id ];
        
        // Check that multiple content document link have been created by the system
        System.AssertEquals(cdl.size()>1, true);
        
    }

 
 }