force-app/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employees__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Resource_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Resource_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apprentice</fullName>
    </customValue>
    <customValue>
        <fullName>Design Drafter</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Principal Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Project Administration</fullName>
    </customValue>
    <customValue>
        <fullName>Project Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Senior Design Drafter</fullName>
    </customValue>
    <customValue>
        <fullName>Senior Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Site Supervisor</fullName>
    </customValue>
    <customValue>
        <fullName>Technician</fullName>
    </customValue>
    <customValue>
        <fullName>Senior Project Manager</fullName>
    </customValue>
    <masterLabel>Resource Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EmployeesDAO.cls
public class EmployeesDAO {

    public static  List<Employees__c> getEmployeesUsingIds(Set<id> employeeIds){
        List<Employees__c> employees = [Select id, 
                                            Role__c 
                                     FROM Employees__c 
                                     Where Id 
                                     In :employeeIds];

        return employees;
        
    }
}