force-app/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employees__c/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employees__c/fields/Department_Code__c.field-meta.xml
<CustomField>
    <fullName>Department_Code__c</fullName>
    <label>Department Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employees__c/fields/Employee_Code__c.field-meta.xml
<CustomField>
    <fullName>Employee_Code__c</fullName>
    <externalId>true</externalId>
    <label>Employee Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-1{0000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/SC_Project_Code__c.field-meta.xml
<CustomField>
    <fullName>SC_Project_Code__c</fullName>
    <label>Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Sync_With_Pronto__c.field-meta.xml
<CustomField>
    <fullName>Sync_With_Pronto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updating Pronto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Actual_Hours__c.field-meta.xml
<CustomField>
    <fullName>Actual_Hours__c</fullName>
    <label>Actual Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Pronto_Account_Code__c.field-meta.xml
<CustomField>
    <fullName>Pronto_Account_Code__c</fullName>
    <formula>ServiceTerritory.Branch_Code__c</formula>
    <label>Pronto Account Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Pronto_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Pronto_Record_ID__c</fullName>
    <description>External key</description>
    <externalId>true</externalId>
    <label>Pronto Record ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/SA_Completed__c.field-meta.xml
<CustomField>
    <fullName>SA_Completed__c</fullName>
    <formula>IF(OR( ISPICKVAL(Service_Appointment__r.Status, &#39;Completed&#39;) , ISPICKVAL(Service_Appointment__r.Status, &#39;Cannot Complete&#39;)), true, false)</formula>
    <label>SA Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/SC_Project_Code__c.field-meta.xml
<CustomField>
    <fullName>SC_Project_Code__c</fullName>
    <label>Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Send_Timesheet__c.field-meta.xml
<CustomField>
    <fullName>Send_Timesheet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Timesheet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Sync_With_Pronto__c.field-meta.xml
<CustomField>
    <fullName>Sync_With_Pronto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updating Pronto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/TECH_Work_Order_Territory_Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>TECH_Work_Order_Territory_Branch_Code__c</fullName>
    <formula>ServiceTerritory.Branch_Code__c</formula>
    <label>Work Order Territory Branch Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Within_Current_Payroll_Period__c.field-meta.xml
<CustomField>
    <fullName>Within_Current_Payroll_Period__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this transaction was validated against Payroll</description>
    <label>Within Current Payroll Period</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Integration_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Integration Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Payroll Period Validated</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Successful</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
        <isActive>false</isActive>
        <label>None</label>
    </customValue>
    <masterLabel>Integration Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WorkOrderLineItemDAO.cls
/**
* 
@author: Imalka fernando - Proquest Consulting
@description: This class handles all data retrieval relative to work order line items
* 
*/
public class WorkOrderLineItemDAO {
    public static  Map<Id,WorkOrderLineItem> getWorkOrderLineItemsUsingWoIds(Set<id> woIds){
        return new Map<Id,WorkOrderLineItem>([  SELECT  Id,
                                                        Within_Current_Payroll_Period__c,
                                                        Sync_With_Pronto__c,
                                                        Actual_Hours__c,
                                                        WorkOrder.WorkOrderNumber,
                                                        LineItemNumber,
                                                        Description,
                                                        StartDate,
                                                        Pronto_Account_Code__c,
                                                        Resource__c,
                                                        Employee__r.Department_Code__c,
                                                        Employee__r.Employee_Code__c,
                                              			Employee__r.Company_Code__c,
                                                        Pronto_Record_Id__c,
                                                        SC_Project_Code__c,
                                                        Resource__r.RelatedRecordId,
                                                        CreatedDate,
                                                        LastModifiedDate,
                                                        SA_Completed__c,
                                                        Send_Timesheet__c,
                                                        Purchase_Order__c,
                                                        TECH_Work_Order_Territory_Branch_Code__c,
                                                        Integration_Status__c
                                                FROM    WorkOrderLineItem 
                                                WHERE   WorkOrderId IN :woIds
                                                AND     StartDate != null
                                                AND     Purchase_Order__c = null]);

    }

    public static List<WorkOrderLineItem> getWorkOrderLineItemsUsingIds(Id woliId){
        return [    SELECT  Id,
                            Within_Current_Payroll_Period__c,
                            Sync_With_Pronto__c,
                            Actual_Hours__c,
                            WorkOrder.WorkOrderNumber,
                            LineItemNumber,
                            Description,
                            StartDate,
                            Pronto_Account_Code__c,
                            Resource__c,
                            Employee__r.Department_Code__c,
                            Employee__r.Employee_Code__c,
                			Employee__r.Company_Code__c,
                            Pronto_Record_Id__c,
                            SC_Project_Code__c,
                            Resource__r.RelatedRecordId,
                            CreatedDate,
                            LastModifiedDate,
                            SA_Completed__c,
                            Send_Timesheet__c,
                            Purchase_Order__c,
                            TECH_Work_Order_Territory_Branch_Code__c
                    FROM    WorkOrderLineItem 
                    WHERE   Id = :woliId];

    }
}