force-app/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employees__c/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employees__c/fields/Department_Code__c.field-meta.xml
<CustomField>
    <fullName>Department_Code__c</fullName>
    <label>Department Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employees__c/fields/Employee_Code__c.field-meta.xml
<CustomField>
    <fullName>Employee_Code__c</fullName>
    <externalId>true</externalId>
    <label>Employee Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Line_of_Business_Code__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business_Code__c</fullName>
    <label>Line of Business Code</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Actual_Hours__c.field-meta.xml
<CustomField>
    <fullName>Actual_Hours__c</fullName>
    <label>Actual Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/SC_Project_Code__c.field-meta.xml
<CustomField>
    <fullName>SC_Project_Code__c</fullName>
    <label>Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/TECH_Work_Order_Territory_Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>TECH_Work_Order_Territory_Branch_Code__c</fullName>
    <formula>ServiceTerritory.Branch_Code__c</formula>
    <label>Work Order Territory Branch Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Timesheet.cls
/**
* 
@author: Imalka Fernando - Proquest Consulting
@description: classes wrapping Work Order line item
* 
*/
public class Timesheet {
    public String id {get;set;} 
    public Decimal hours {get;set;} 
    public Decimal overtime_hours {get;set;} 
    public Decimal double_time_hours {get;set;} 
    public Decimal public_holiday_hours {get;set;}
    public String work_order {get;set;} 
    public String trans_number {get;set;} 
    public String description {get;set;} 
    public String work_date {get;set;} 
    public String company {get;set;} 
    public String territory_company {get;set;} 
    public String line_of_business_code {get;set;} 
    public String employee_code {get;set;} 
    public String record_id {get;set;} 
    public String project_code {get;set;}
    public Long timestamp; 

    public static Timesheet WrappedWOLI(WorkOrderLineItem woliIn, User resource){
        Timesheet woliWrapped = new Timesheet();
        
        woliWrapped.id = woliIn.Id;
        //woliWrapped.hours = woliIn.Actual_Hours__c.setScale(2);
        
        woliWrapped.hours = woliIn.Normal_Time__c.setScale(2);
        woliWrapped.overtime_hours = woliIn.Overtime__c.setScale(2);
        woliWrapped.double_time_hours = woliIn.Double_Time__c.setScale(2);
        woliWrapped.public_holiday_hours = woliIn.Public_Holiday__c.setScale(2);
        
        woliWrapped.work_order = woliIn.WorkOrder.WorkOrderNumber;
        woliWrapped.trans_number = woliIn.LineItemNumber;
        woliWrapped.description = woliIn.Description;
        if(woliIn.StartDate != null){
            //date format: year/month/day
            woliWrapped.work_date = (woliIn.StartDate != null ? string.valueOf(date.newinstance(woliIn.StartDate.year(), woliIn.StartDate.month(), woliIn.StartDate.day())) : null );
        }
        
        woliWrapped.company = woliIn.Employee__c != null ? woliIn.Employee__r.Company_Code__c : resource.Company_Code__c;
        woliWrapped.territory_company = woliIn.TECH_Work_Order_Territory_Branch_Code__c ;
        woliWrapped.line_of_business_code = woliIn.Employee__c != null ? woliIn.Employee__r.Department_Code__c : resource.Line_of_Business_Code__c;
        woliWrapped.employee_code = woliIn.Employee__c != null ? woliIn.Employee__r.Employee_Code__c : resource.EmployeeNumber;
        woliWrapped.project_code = woliIn.SC_Project_Code__c;

        if(woliIn.LastModifiedDate != null){
            woliWrapped.timestamp = woliIn.LastModifiedDate.getTime();
        }
        
        if(woliIn.createdDate != null){
            woliWrapped.timestamp = woliIn.createdDate.getTime();
        }
        
        if(woliWrapped.timestamp == null)
        {
            woliWrapped.timestamp = System.now().getTime();
        }
        
        return woliWrapped;
    }
}