force-app/main/default/objects/Account/fields/Account_Payable_Contact__c.field-meta.xml
<CustomField>
    <fullName>Account_Payable_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Payable Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3 AND 5 AND 6) OR (2 AND 4 AND 5 AND 6)</booleanFilter>
        <errorMessage>There is no active service contract of this customer, please create or choose template contract.</errorMessage>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>ServiceContract.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>ServiceContract.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Template_Contract_RT</value>
        </filterItems>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>ServiceContract.Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>ServiceContract.Type__c</field>
            <operation>equals</operation>
            <value>Bronze Support</value>
        </filterItems>
        <filterItems>
            <field>ServiceContract.StartDate</field>
            <operation>lessOrEqual</operation>
            <valueField>ServiceContract.NOW__c</valueField>
        </filterItems>
        <filterItems>
            <field>ServiceContract.EndDate</field>
            <operation>greaterOrEqual</operation>
            <valueField>ServiceContract.NOW__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <formula>TEXT(Product2.Contract_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <formula>TEXT(Product2.Resource_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Service_Time__c.field-meta.xml
<CustomField>
    <fullName>Service_Time__c</fullName>
    <formula>TEXT(Product2.Service_Time__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Usage_per_hour__c.field-meta.xml
<CustomField>
    <fullName>Usage_per_hour__c</fullName>
    <label>Usage per hour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Resource_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Service_Time__c.field-meta.xml
<CustomField>
    <fullName>Service_Time__c</fullName>
    <label>Service Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Hours</fullName>
            </value>
            <value>
                <fullName>Overtime</fullName>
            </value>
            <value>
                <fullName>Night Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-1{0000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MAT</fullName>
                <label>Materials</label>
            </value>
            <value>
                <fullName>SUB</fullName>
                <label>Subcontrator</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Annual_Service_Amount__c.field-meta.xml
<CustomField>
    <fullName>Annual_Service_Amount__c</fullName>
    <label>Annual Service Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Billing_Cycle_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Cycle_Type__c</fullName>
    <label>Billing Cycle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Advance</fullName>
            </value>
            <value>
                <fullName>In Arrears</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Contract_Billing_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Contract_Billing_Cycle__c</fullName>
    <label>Contract Billing Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Next_Contract_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Contract_Billing_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Next Contract Billing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Night_Time__c.field-meta.xml
<CustomField>
    <fullName>Night_Time__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Night Time</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Service_Contracts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Normal_Time__c.field-meta.xml
<CustomField>
    <fullName>Normal_Time__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Normal Time</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Service_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Number_of_Pre_Purchased_Hours__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Pre_Purchased_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Pre-Purchased Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Overtime__c.field-meta.xml
<CustomField>
    <fullName>Overtime__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Overtime</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Service_Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Service Contracts</relationshipLabel>
    <relationshipName>Service_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Number_of_Pre_Purchased_Hours__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Pre_Purchased_Hours__c</fullName>
    <formula>ServiceContract.Number_of_Pre_Purchased_Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Pre-Purchased Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Actual_Hours__c.field-meta.xml
<CustomField>
    <fullName>Actual_Hours__c</fullName>
    <label>Actual Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Billable_Hours__c.field-meta.xml
<CustomField>
    <fullName>Billable_Hours__c</fullName>
    <label>Billable Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Usage_per_hour__c.field-meta.xml
<CustomField>
    <fullName>Usage_per_hour__c</fullName>
    <formula>PricebookEntry.Usage_per_hour__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Usage per hour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Within_Current_Payroll_Period__c.field-meta.xml
<CustomField>
    <fullName>Within_Current_Payroll_Period__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this transaction was validated against Payroll</description>
    <label>Within Current Payroll Period</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Contract_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bronze Support</fullName>
    </customValue>
    <customValue>
        <fullName>Silver Support</fullName>
    </customValue>
    <customValue>
        <fullName>Gold Support</fullName>
    </customValue>
    <customValue>
        <fullName>Platinum Support</fullName>
    </customValue>
    <masterLabel>Contract Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Resource_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apprentice</fullName>
    </customValue>
    <customValue>
        <fullName>Design Drafter</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Principal Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Project Administration</fullName>
    </customValue>
    <customValue>
        <fullName>Project Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Senior Design Drafter</fullName>
    </customValue>
    <customValue>
        <fullName>Senior Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Site Supervisor</fullName>
    </customValue>
    <customValue>
        <fullName>Technician</fullName>
    </customValue>
    <customValue>
        <fullName>Senior Project Manager</fullName>
    </customValue>
    <masterLabel>Resource Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ServiceAppointmentTriggerHandlerTest.cls
@isTest(SeeAllData=true) 
public class ServiceAppointmentTriggerHandlerTest {
    static testmethod void serviceAppointmentCompletionTest(){
        id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Constants.ACC_COMPANY_RT).getRecordTypeId();
        
        ServiceTerritory territory = [Select Id From ServiceTerritory Where Name = 'SA'];
         
        List<Account> newAccounts = new List<Account>(); 
        newAccounts = TestDataUtility.createAccounts(1,accRecordTypeId, false);
        newAccounts[0].Service_Territory__c = territory.id;
        insert newAccounts;

        List<Contact> newContacts = new List<Contact>();
        newContacts = TestDataUtility.createContacts(1,newAccounts[0].id, false);
        newContacts.get(0).Email = 'pq@consulting.com';
        insert newContacts;

        //update account details
        newAccounts[0].Account_Payable_Contact__c  = newContacts[0].Id;
        update newAccounts;
        
        List<Product2> newProducts = new List<Product2>(); 
        newProducts = TestDataUtility.createProducts(12 , 'Test', false);
        newProducts[0].Resource_Type__c =  Constants.TYPE_TECHNICIAN;
        newProducts[0].Service_Time__c  =  Constants.SERVICE_BUSINESS;
        newProducts[0].Contract_Type__c =  Constants.TYPE_SILVER;
        newProducts[1].Resource_Type__c =  Constants.TYPE_TECHNICIAN;
        newProducts[1].Service_Time__c  =  Constants.SERVICE_OVERTIME;   
        newProducts[1].Contract_Type__c =  Constants.TYPE_SILVER ;
        newProducts[2].Resource_Type__c =  Constants.TYPE_TECHNICIAN;
        newProducts[2].Service_Time__c  =  Constants.SERVICE_NIGHT;   
        newProducts[2].Contract_Type__c =  Constants.TYPE_SILVER;      
        newProducts[3].Resource_Type__c =  Constants.TYPE_ENGINEER;
        newProducts[3].Service_Time__c  =  Constants.SERVICE_BUSINESS;
        newProducts[3].Contract_Type__c =  Constants.TYPE_SILVER;
        newProducts[4].Resource_Type__c =  Constants.TYPE_ENGINEER;
        newProducts[4].Service_Time__c  =  Constants.SERVICE_OVERTIME;   
        newProducts[4].Contract_Type__c =  Constants.TYPE_SILVER ;
        newProducts[5].Resource_Type__c =  Constants.TYPE_ENGINEER;
        newProducts[5].Service_Time__c  =  Constants.SERVICE_NIGHT;   
        newProducts[5].Contract_Type__c =  Constants.TYPE_SILVER;     
        insert newProducts;   
        
        Pricebook2 pricebook = new Pricebook2 (Name = 'Silver PB', IsActive = true, Service_Territory__c = territory.id, Contract_Type__c = Constants.TYPE_SILVER);
        
        insert pricebook;
        
        Pricebook2 Standardpricebook = new Pricebook2( id = Test.getStandardPricebookId());
        update Standardpricebook ; 
        
        System.AssertNotEquals(NULL, Standardpricebook.id);
        
        List <PricebookEntry> pbEntries = new List <PricebookEntry>();
        Decimal unitPrice = 100;
        
        for(Product2 p :newProducts){        
            PricebookEntry entry = new PricebookEntry (Pricebook2Id = Standardpricebook.id, Product2id = p.id, UnitPrice =unitPrice, IsActive = true, Usage_per_hour__c =1.5 );
            unitPrice = unitPrice +1;
            pbEntries.add(entry);     
        }
        insert pbEntries;   
        
        for(Product2 p :newProducts){        
            PricebookEntry entry = new PricebookEntry (Pricebook2Id = pricebook.id, Product2id = p.id, UnitPrice =unitPrice, IsActive = true, Usage_per_hour__c =1.5 );
            unitPrice = unitPrice +1;
            pbEntries.add(entry);     
        }
        upsert pbEntries;    
        
        BusinessHours normalTimeBH  = BusinessHoursDAO.getBUUsingName('Adelaide Time: 07:30-16:00 Mon-Fri');        
        BusinessHours overtimeBH    = BusinessHoursDAO.getBUUsingName('Adelaide Time: 16:00-00:00 Mon-Fri 7:30-00:00 Sat-Sun'); 
        BusinessHours nighttimeBH   = BusinessHoursDAO.getBUUsingName('Adelaide Time: 00:00-07:30 Mon-Sun'); 
        
        BusinessHours normalTimeBH2 = BusinessHoursDAO.getBUUsingName('Adelaide Time: 06:00-18:00 Mon-Fri');    
        BusinessHours overtimeBH2   = BusinessHoursDAO.getBUUsingName('Adelaide Time: Any time after Business Hours');         
        
        List<ServiceContract> newServiceContracts = new List<ServiceContract>();
        newServiceContracts = TestDataUtility.createServiceContract(1, newAccounts[0].id, newContacts[0].id, territory.id, false);
        newServiceContracts[0].Normal_Time__c = normalTimeBH.id;
        newServiceContracts[0].Overtime__c = overtimeBH.id;
        newServiceContracts[0].Night_Time__c = nighttimeBH.id;
        newServiceContracts[0].Type__c = Constants.TYPE_SILVER;
        newServiceContracts[0].Number_of_Pre_Purchased_Hours__c = 0;
        newServiceContracts[0].Service_Territory__c =territory.id;
        newServiceContracts[0].Next_Contract_Billing_Date__c = System.Today();
        newServiceContracts[0].Annual_Service_Amount__c = 12000;
        newServiceContracts[0].Contract_Billing_Cycle__c = Constants.CYCLE_MONTHLY;
        newServiceContracts[0].Billing_Cycle_Type__c = Constants.CYCLE_TYPE_IN_ADVANCE;

        insert newServiceContracts;
                        
         
        List<Case> newCases = new List<Case>();
        newCases = TestDataUtility.createCases(1, newAccounts[0].id, newContacts[0].id, newServiceContracts[0].id, false);
        newCases[0].Service_Territory__c = territory.id;
       
        List<WorkType> newWorkTypes = new List<WorkType>(); 
        newWorkTypes = TestDataUtility.createWorkType(1,'PLC', true);
        
        List<WorkOrder> newWorkOrders = new List<WorkOrder>();
        newWorkOrders = TestDataUtility.createWorkOrders(1, newAccounts[0].id, newContacts[0].id, newCases[0].id, newWorkTypes[0].id, newServiceContracts[0].id, true);
        
        List <ServiceAppointment> generatedSAS = [SELECT id, ParentRecordId , Status FROM ServiceAppointment WHERE ParentRecordId = :newWorkOrders[0].id];
        
        List<User> newUsers = new List<User>(); 
        newUsers = TestDataUtility.createUsers(1, true);      
        
        List<ServiceResource> newSR = new List<ServiceResource>(); 
        newSR = TestDataUtility.createServiceResource(1, newUsers[0].id, true);    
        
        List<Employees__c> newEmployees = new List<Employees__c>(); 
        newEmployees = TestDataUtility.createEmployees(1, Constants.TYPE_ENGINEER, true);   
        
        DateTime start = datetime.newinstance(2019, 12, 31, 12, 0, 0);
        WorkOrderLineItem woli = new WorkOrderLineItem( WorkOrderid = newWorkOrders[0].id,
                                                        Resource__c = newSR[0].id,
                                                        Case__c = newCases[0].id, 
                                                        StartDate = start,
                                                        EndDate = start + 24/16,
                                                        Billable_Hours__c = 16,
                                                        Actual_Hours__c =16,
                                                        Within_Current_Payroll_Period__c = true,
                                                        Service_Contract__c = newServiceContracts[0].id
                                                        );        
        insert woli;
        
        List <WorkOrderLineItem> wolis = [Select PricebookEntryId, UnitPrice FROM WorkOrderLineItem WHERE WorkOrderId = :newWorkOrders[0].id];
        
        // Check that multiple work order line items have been created for 1 record entered
        System.AssertEquals(wolis.size()>1, true);
        
        
        //Create Service Contract line item only for 1 contract
        Service_Contract_Line_Item__c scli = new Service_Contract_Line_Item__c (Quantity__c =1, Service_Contract__c= newServiceContracts[0].id ,  Service_Rate__c = 12000, Item_Code__c = 'EQU001');
        insert  scli;
        
        
        // Launch Nightly job for SA
        String CRON_EXP = '0 0 0 15 3 ? 2022';
        String jobId = System.schedule('ScheduledSAContractFees', CRON_EXP, new ContractFeesJobSA());   
        
        CreateContractFeesBatch  sabatchToExecute = new CreateContractFeesBatch (territory.id); 
        Id batchId = Database.executeBatch(sabatchToExecute);
        
        ServiceAppointment generatedSA = generatedSAS.get(0);
        generatedSA.Status = Constants.SERVICE_APPOINMENT_STATUS_ACCEPTED;
        update generatedSA;

        generatedSA.Status = Constants.SERVICE_APPOINMENT_STATUS_INPROGRESS;
        update generatedSA;
        
        // Test SA validation Complete WO start
        
        ServiceAppointment sa = new ServiceAppointment(parentrecordid =generatedSA.parentrecordid);
        insert sa;
        
        generatedSA.Status = Constants.SERVICE_APPOINMENT_STATUS_COMPLETE;
        generatedSA.Action_Taken__c = 'Actions';
        generatedSA.Work_Order_Completed__c = 'Yes';
        generatedSA.Transaction_Completed__c = true;
        
        try{
            update generatedSA;     
        }  
        catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains('You cannot Complete the work order as other Service Appointments are still opened') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        } 
        
        sa  = [SELECT id  FROM ServiceAppointment WHERE ParentRecordId = :newWorkOrders[0].id AND Status = 'None' limit 1];
        delete sa;        
        // Test SA validation Complete WO end

        // Test SA validation Complete Where Open PO exist start
		Purchase_Order__c po = new Purchase_Order__c (Service_Appointment__c = generatedSA.id, Work_Order__c =newWorkOrders[0].id , Service_Territory__c = territory.id);
        insert po;
        
        Purchase_Order_Line_Item__c poli = new Purchase_Order_Line_Item__c(Cost__c = 3500, Quantity__c = 6, Purchase_Order__c = po.id );
        insert poli;
        
        po.Status__c = 'Approval Pending';
        update po;
        
        try{
            update generatedSA;     
        }  
        catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains('You cannot Complete the work order as some Purchase Orders are still opened') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        } 
        
        delete po;
        
        // Test SA validation Complete Where Open PO exist end

        generatedSA.Status = Constants.SERVICE_APPOINMENT_STATUS_INPROGRESS;
        generatedSA.Action_Taken__c = 'Actions';
        update generatedSA;
        generatedSA.Work_Order_Completed__c = 'Yes';
        generatedSA.Transaction_Completed__c = true;
        generatedSA.Status = Constants.SERVICE_APPOINMENT_STATUS_COMPLETE;
        update generatedSA;
        

        WorkOrderLineItem generatedWOLI = [SELECT id, Status FROM WorkOrderLineItem LIMIT 1];
        generatedWOLI = WorkOrderLineItemDAO.getWorkOrderLineItemsUsingIds(generatedWOLI.Id).get(0);
        Test.startTest();
            SynchWithPronto syncjob = new SynchWithPronto(generatedWOLI , 'WorkOrderLineItem', null);
            ID syncjobID = System.enqueueJob(syncjob);
        Test.stopTest();
        
    }
}