force-app/main/default/objects/Account/fields/Account_Payable_Contact__c.field-meta.xml
<CustomField>
    <fullName>Account_Payable_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Payable Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Integration Pending</fullName>
            </value>
            <value>
                <fullName>Incomplete Information</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
                <default>true</default>
                <label>Not Applicable</label>
            </value>
            <value>
                <fullName>Waiting Confirmation</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
            <value>
                <fullName>Success</fullName>
                <isActive>false</isActive>
                <label>Success</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_With_Pronto__c.field-meta.xml
<CustomField>
    <fullName>Sync_With_Pronto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updating Pronto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Account Payable Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/Pronto_Territory_Code__c.field-meta.xml
<CustomField>
    <fullName>Pronto_Territory_Code__c</fullName>
    <externalId>true</externalId>
    <label>Pronto Territory Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTriggerTest.cls
/*******************************************************************************
* @author          Cyrille Jeufo (Proquest Consulting)
* @date            21.Nov.2019        
* @description     Testing the SupplierAPI class
• @revision 
• v1.0      - Refer purpose 
*******************************************************************************/
@IsTest
public class AccountTriggerTest{
    @isTest static void testWithNoTerritory(){
        
        id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Constants.ACC_COMPANY_RT).getRecordTypeId();
        
        Test.setMock(HttpCalloutMock.class, new CustomerHttpCalloutMock()); 
        List<Account> newAccounts = new List<Account>(); 
        newAccounts = TestDataUtility.createAccounts(1,accRecordTypeId, true);
        
        List<Contact> newContacts = new List<Contact>();
        newContacts = TestDataUtility.createContacts(1,newAccounts[0].id, false);
        newContacts.get(0).Email = 'pq@consulting.com';
        newContacts[0].Primary__c = true;
        insert newContacts;
        newAccounts[0].Integration_Status__c = 'Failed';
        newAccounts[0].Sync_With_Pronto__c = false;
        newAccounts[0].Account_Payable_Contact__c = newContacts[0].Id;
        Test.startTest();
        update newAccounts;
        Test.stopTest();
        Account acc = [Select Id From Account where Id =:newAccounts[0].Id ];
    }
    
    
    @isTest static void testWithTerritory(){
        
        id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Constants.ACC_COMPANY_RT).getRecordTypeId();
        
        Test.setMock(HttpCalloutMock.class, new CustomerHttpCalloutMock()); 
        
        List<Account> newAccounts = new List<Account>(); 
        newAccounts = TestDataUtility.createAccounts(1,accRecordTypeId, true);
        
        List<Contact> newContacts = new List<Contact>();
        newContacts = TestDataUtility.createContacts(1,newAccounts[0].id, false);
        newContacts.get(0).Email = 'pq@consulting.com';
        newContacts[0].Primary__c = true;
        insert newContacts;
        newAccounts[0].Integration_Status__c = 'Failed';
        newAccounts[0].Sync_With_Pronto__c = false;
        newAccounts[0].Account_Payable_Contact__c = newContacts[0].Id;
        
        List<OperatingHours> newOPs = new List<OperatingHours>(); 
        newOPs = TestDataUtility.createOperatingHour(1,'SA Operating hours', true);
        
        List<ServiceTerritory> newSTs = new List<ServiceTerritory>(); 
        newSTs = TestDataUtility.createSTerritories(1,'SA',newOPs[0].id , true);
        newSTs[0].Pronto_Territory_Code__c = '700';
        update newSTs;
        Test.startTest();
        newAccounts[0].Sync_With_Pronto__c = true;
        newAccounts[0].Service_Territory__c = newSTs[0].id;
        update newAccounts;
        Test.stopTest();
        Account acc = [Select Id,Integration_Status__c, Sync_With_Pronto__c From Account where Id =:newAccounts[0].Id ];
        
    }
    
}