force-app/main/default/objects/Account/fields/Account_Name_Lower__c.field-meta.xml
<CustomField>
    <fullName>Account_Name_Lower__c</fullName>
    <formula>LOWER( Name )</formula>
    <label>Account Name Lower</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pronto_Account_Code__c.field-meta.xml
<CustomField>
    <fullName>Pronto_Account_Code__c</fullName>
    <externalId>true</externalId>
    <label>Account Code</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AccountDAO.cls
public class AccountDAO {
    public static  List<Account> getAccountByName(String accountName){
        List<Account> accs = [   Select  Id, 
                                                Name 
                                        From    Account 
                                        Where   Account_Name_Lower__c = :accountName];

        return accs;
        
    }

    public static List<Account> getCaseAccountByTerritory(String serviceTerritory){
        List<Account> customers = [ Select  Id 
                                    From    Account 
                                    Where   Name LIKE 'Cash Sales%' 
                                    AND     Service_Territory__r.Name = :serviceTerritory];
        return customers;
    }

    public static List<Account> getAccountByProntoCode(String accCode){
        List<Account> customers = [ Select  Id
                                    From    Account
                                    Where   Pronto_Account_Code__c = :accCode ];
        return customers;                                    
    }
}