force-app/main/default/objects/Account/fields/Account_Payable_Contact__c.field-meta.xml
<CustomField>
    <fullName>Account_Payable_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Payable Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Supplier_Account_RT.recordType-meta.xml
<RecordType>
    <fullName>Supplier_Account_RT</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Aggregate_Billing_Format__mdt/Aggregate_Billing_Format__mdt.object-meta.xml
<CustomObject>
    <label>Aggregate Billing Format</label>
    <pluralLabel>Aggregate Billing Format</pluralLabel>
</CustomObject>

force-app/main/default/objects/Pricebook2/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <formula>TEXT(Product2.Contract_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <formula>TEXT(Product2.Resource_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Service_Time__c.field-meta.xml
<CustomField>
    <fullName>Service_Time__c</fullName>
    <formula>TEXT(Product2.Service_Time__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Usage_per_hour__c.field-meta.xml
<CustomField>
    <fullName>Usage_per_hour__c</fullName>
    <label>Usage per hour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Resource_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Service_Time__c.field-meta.xml
<CustomField>
    <fullName>Service_Time__c</fullName>
    <label>Service Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Hours</fullName>
            </value>
            <value>
                <fullName>Overtime</fullName>
            </value>
            <value>
                <fullName>Night Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>This object will be used to create records for the purpose of invoicing</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/Sales_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <description>Parent Sales Order</description>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Aggregate_Billing_Format__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Billing_Format__c</fullName>
    <label>Aggregate Billing Format</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Annual_Service_Amount__c.field-meta.xml
<CustomField>
    <fullName>Annual_Service_Amount__c</fullName>
    <label>Annual Service Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Billing_Cycle_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Cycle_Type__c</fullName>
    <label>Billing Cycle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Advance</fullName>
            </value>
            <value>
                <fullName>In Arrears</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Billing_Terms__c.field-meta.xml
<CustomField>
    <fullName>Billing_Terms__c</fullName>
    <label>Billing Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Aggregated Billing</fullName>
            </value>
            <value>
                <fullName>Individual Work Orders</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
                <isActive>false</isActive>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>Yearly</fullName>
                <isActive>false</isActive>
                <label>Yearly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Contract_Billing_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Contract_Billing_Cycle__c</fullName>
    <label>Contract Billing Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Next_Contract_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Contract_Billing_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Next Contract Billing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Night_Time__c.field-meta.xml
<CustomField>
    <fullName>Night_Time__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Night Time</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Service_Contracts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Normal_Time__c.field-meta.xml
<CustomField>
    <fullName>Normal_Time__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Normal Time</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Service_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Number_of_Pre_Purchased_Hours__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Pre_Purchased_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Pre-Purchased Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Overtime__c.field-meta.xml
<CustomField>
    <fullName>Overtime__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Overtime</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Service_Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Service Contracts</relationshipLabel>
    <relationshipName>Service_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <externalId>true</externalId>
    <label>Branch Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/Pronto_Territory_Code__c.field-meta.xml
<CustomField>
    <fullName>Pronto_Territory_Code__c</fullName>
    <externalId>true</externalId>
    <label>Pronto Territory Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Number_of_Pre_Purchased_Hours__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Pre_Purchased_Hours__c</fullName>
    <formula>ServiceContract.Number_of_Pre_Purchased_Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Pre-Purchased Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Total_Billable_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Billable_Hours__c</fullName>
    <label>Total Billable Hours</label>
    <summarizedField>WorkOrderLineItem.Billable_Hours__c</summarizedField>
    <summaryForeignKey>WorkOrderLineItem.WorkOrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/globalValueSets/Contract_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bronze Support</fullName>
    </customValue>
    <customValue>
        <fullName>Silver Support</fullName>
    </customValue>
    <customValue>
        <fullName>Gold Support</fullName>
    </customValue>
    <customValue>
        <fullName>Platinum Support</fullName>
    </customValue>
    <masterLabel>Contract Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Resource_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apprentice</fullName>
    </customValue>
    <customValue>
        <fullName>Design Drafter</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Principal Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Project Administration</fullName>
    </customValue>
    <customValue>
        <fullName>Project Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Senior Design Drafter</fullName>
    </customValue>
    <customValue>
        <fullName>Senior Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Site Supervisor</fullName>
    </customValue>
    <customValue>
        <fullName>Technician</fullName>
    </customValue>
    <customValue>
        <fullName>Senior Project Manager</fullName>
    </customValue>
    <masterLabel>Resource Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AggregateBillingFormatControllerTest.cls
@isTest
public class AggregateBillingFormatControllerTest {

    @TestSetup
    static void setup() {
        id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Constants.ACC_COMPANY_RT).getRecordTypeId();
        id supRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Constants.SUPPLIER_ACCOUNT_RT).getRecordTypeId();
        
        
        List<OperatingHours> newOPs = new List<OperatingHours>(); 
        newOPs = TestDataUtility.createOperatingHour(1,'SA Operating hours', true);

        ServiceTerritory territory = new ServiceTerritory(OperatingHoursId = newOPs[0].id, Name ='SA' , Pronto_Territory_Code__c = '700', IsActive = true, Branch_Code__c = '5');
        insert territory;
         
        List<Account> newAccounts = new List<Account>(); 
        newAccounts = TestDataUtility.createAccounts(1,accRecordTypeId, false);
        newAccounts[0].Service_Territory__c = territory.id;
        insert newAccounts;

        List<Account> newSupplier = new List<Account>(); 
        newSupplier = TestDataUtility.createAccounts(1,supRecordTypeId, false);
        newSupplier[0].Service_Territory__c = territory.id;
        insert newSupplier;

        List<Contact> newContacts = new List<Contact>();
        newContacts = TestDataUtility.createContacts(1,newAccounts[0].id, false);
        newContacts.get(0).Email = 'pq@consulting.com';
        insert newContacts;

        //update account details
        newAccounts[0].Account_Payable_Contact__c  = newContacts[0].Id;
        update newAccounts;
        
        List<Product2> newProducts = new List<Product2>(); 
        newProducts = TestDataUtility.createProducts(12 , 'Test', false);
        newProducts[0].Resource_Type__c =  Constants.TYPE_TECHNICIAN;
        newProducts[0].Service_Time__c  =  Constants.SERVICE_BUSINESS;
        newProducts[0].Contract_Type__c =  Constants.TYPE_SILVER;
        newProducts[1].Resource_Type__c =  Constants.TYPE_TECHNICIAN;
        newProducts[1].Service_Time__c  =  Constants.SERVICE_OVERTIME;   
        newProducts[1].Contract_Type__c =  Constants.TYPE_SILVER ;
        newProducts[2].Resource_Type__c =  Constants.TYPE_TECHNICIAN;
        newProducts[2].Service_Time__c  =  Constants.SERVICE_NIGHT;   
        newProducts[2].Contract_Type__c =  Constants.TYPE_SILVER;      
        newProducts[3].Resource_Type__c =  Constants.TYPE_ENGINEER;
        newProducts[3].Service_Time__c  =  Constants.SERVICE_BUSINESS;
        newProducts[3].Contract_Type__c =  Constants.TYPE_SILVER;
        newProducts[4].Resource_Type__c =  Constants.TYPE_ENGINEER;
        newProducts[4].Service_Time__c  =  Constants.SERVICE_OVERTIME;   
        newProducts[4].Contract_Type__c =  Constants.TYPE_SILVER ;
        newProducts[5].Resource_Type__c =  Constants.TYPE_ENGINEER;
        newProducts[5].Service_Time__c  =  Constants.SERVICE_NIGHT;   
        newProducts[5].Contract_Type__c =  Constants.TYPE_SILVER;     
        insert newProducts;   
        
        Pricebook2 pricebook = new Pricebook2 (Name = 'Silver PB', IsActive = true, Service_Territory__c = territory.id, Contract_Type__c = Constants.TYPE_SILVER);
        
        insert pricebook;
        
        Pricebook2 Standardpricebook = new Pricebook2( id = Test.getStandardPricebookId());
        update Standardpricebook ; 
        
        System.AssertNotEquals(NULL, Standardpricebook.id);
        
        List <PricebookEntry> pbEntries = new List <PricebookEntry>();
        Decimal unitPrice = 100;
        
        for(Product2 p :newProducts){        
            PricebookEntry entry = new PricebookEntry (Pricebook2Id = Standardpricebook.id, Product2id = p.id, UnitPrice =unitPrice, IsActive = true, Usage_per_hour__c =1.5 );
            unitPrice = unitPrice +1;
            pbEntries.add(entry);     
        }
        insert pbEntries;   
        
        for(Product2 p :newProducts){        
            PricebookEntry entry = new PricebookEntry (Pricebook2Id = pricebook.id, Product2id = p.id, UnitPrice =unitPrice, IsActive = true, Usage_per_hour__c =1.5 );
            unitPrice = unitPrice +1;
            pbEntries.add(entry);     
        }
        upsert pbEntries;    
        
        BusinessHours normalTimeBH  = BusinessHoursDAO.getBUUsingName('Adelaide Time: 07:30-16:00 Mon-Fri');        
        BusinessHours overtimeBH    = BusinessHoursDAO.getBUUsingName('Adelaide Time: 16:00-00:00 Mon-Fri 7:30-00:00 Sat-Sun'); 
        BusinessHours nighttimeBH   = BusinessHoursDAO.getBUUsingName('Adelaide Time: 00:00-07:30 Mon-Sun'); 
        
        BusinessHours normalTimeBH2 = BusinessHoursDAO.getBUUsingName('Adelaide Time: 06:00-18:00 Mon-Fri');    
        BusinessHours overtimeBH2   = BusinessHoursDAO.getBUUsingName('Adelaide Time: Any time after Business Hours');         
        
        List<ServiceContract> newServiceContracts = new List<ServiceContract>();
        newServiceContracts = TestDataUtility.createServiceContract(1, newAccounts[0].id, newContacts[0].id, territory.id, false);
        newServiceContracts[0].Normal_Time__c = normalTimeBH.id;
        newServiceContracts[0].Overtime__c = overtimeBH.id;
        newServiceContracts[0].Night_Time__c = nighttimeBH.id;
        newServiceContracts[0].Type__c = Constants.TYPE_SILVER;
        newServiceContracts[0].Number_of_Pre_Purchased_Hours__c = 0;
        newServiceContracts[0].Service_Territory__c =territory.id;
        newServiceContracts[0].Next_Contract_Billing_Date__c = System.Today();
        newServiceContracts[0].Annual_Service_Amount__c = 12000;
        newServiceContracts[0].Contract_Billing_Cycle__c = Constants.CYCLE_MONTHLY;
        newServiceContracts[0].Billing_Cycle_Type__c =Constants.CYCLE_TYPE_IN_ADVANCE;
        newServiceContracts[0].Aggregate_Billing_Format__c = 'Total_Billable_Hours__c:Hours,';
        newServiceContracts[0].Billing_Terms__c = Constants.CYCLE_AGGREGATE;
        insert newServiceContracts;
        
        List<Case> newCases = new List<Case>();
        newCases = TestDataUtility.createCases(1, newAccounts[0].id, newContacts[0].id, newServiceContracts[0].id, false);
        newCases[0].Service_Territory__c = territory.id;
       
        List<WorkType> newWorkTypes = new List<WorkType>(); 
        newWorkTypes = TestDataUtility.createWorkType(1,'PLC', true);
        
        List<WorkOrder> newWorkOrders = new List<WorkOrder>();
        newWorkOrders = TestDataUtility.createWorkOrders(1, newAccounts[0].id, newContacts[0].id, newCases[0].id, newWorkTypes[0].id, newServiceContracts[0].id, true);
        newWorkOrders.get(0).Status  = Constants.WORK_ORDER_STATUS_READY_TO_INVOICE;
        update newWorkOrders;
        
        List <ServiceAppointment> generatedSAS = [SELECT id, Status FROM ServiceAppointment WHERE ParentRecordId = :newWorkOrders[0].id];
        
                        
    }

    static testmethod void testBillingFormatMethods() { 
        List<ServiceContract> serviceContracts = [Select Id From ServiceContract LIMIT 1];
        Test.startTest();
            Map<String,Aggregate_Billing_Format__mdt> billingFormats = AggregateBillingFormatController.getBillingFormatsMap();
            Map<String,Aggregate_Billing_Format__mdt> billingFormatMap = AggregateBillingFormatController.getBillingFormatsMapByMasterLabel();
            List<String> formats = AggregateBillingFormatController.getBillingFormats();
            ServiceContract sc = AggregateBillingFormatController.getServiceContract(serviceContracts.get(0).Id);
            List<AggregateBillingFormatController.BillingFormat> bilFormats = AggregateBillingFormatController.getServiceContractBillingFormat(serviceContracts.get(0).Id);
            sc = AggregateBillingFormatController.saveServiceContract(sc, '[{"value":"Billable Hours","label":"Hours"},{"value":"Salesforce Work Order Number","label":"Salesforce Work Order No"}]');
            System.assertEquals('Total_Billable_Hours__c:Hours,WorkOrderNumber:Salesforce Work Order No,', sc.Aggregate_Billing_Format__c);
        Test.stopTest();
        
        
    }
    
    static testmethod void testCreateAggregateSalesOrder() { 
        List<ServiceContract> serviceContracts = [Select Id,AccountId,Service_Territory__c From ServiceContract LIMIT 1];
        Test.startTest();
            List<WorkOrder> wOrders = AggregateBillingFormatController.getWorkOrderForContractWithStatus(serviceContracts.get(0).Id, Constants.WORK_ORDER_STATUS_READY_TO_INVOICE);
            System.assertEquals(1, wOrders.size());
        	Id soId = AggregateBillingFormatController.createSalesOrder(serviceContracts.get(0),'[\"'+wOrders.get(0).Id+'\"]');
        	System.assert(soId != null);
        	List<Sales_Order_Line_Item__c> soLines = [Select Id From Sales_Order_Line_Item__c Where Sales_Order__c = :soId AND Work_Order__c = :wOrders.get(0).Id];
        	System.assertEquals(1, soLines.size());
        	wOrders = [Select Id From WorkOrder Where ID = :wOrders.get(0).Id AND Sales_Order__c = :soId];
        	System.assertEquals(1, wOrders.size());        
        Test.stopTest();
        
        
    }
}