force-app/main/default/objects/Account/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No supply</label>
            </value>
            <value>
                <fullName>L</fullName>
                <label>Legal Action</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Site_City_Suburb__c.field-meta.xml
<CustomField>
    <fullName>Site_City_Suburb__c</fullName>
    <label>Site City/Suburb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Postcode__c.field-meta.xml
<CustomField>
    <fullName>Site_Postcode__c</fullName>
    <label>Site Postcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_State__c.field-meta.xml
<CustomField>
    <fullName>Site_State__c</fullName>
    <label>Site State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Street__c.field-meta.xml
<CustomField>
    <fullName>Site_Street__c</fullName>
    <label>Site Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3 AND 5 AND 6) OR (2 AND 4 AND 5 AND 6)</booleanFilter>
        <errorMessage>There is no active service contract of this customer, please create or choose template contract.</errorMessage>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>ServiceContract.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>ServiceContract.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Template_Contract_RT</value>
        </filterItems>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>ServiceContract.Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>ServiceContract.Type__c</field>
            <operation>equals</operation>
            <value>Bronze Support</value>
        </filterItems>
        <filterItems>
            <field>ServiceContract.StartDate</field>
            <operation>lessOrEqual</operation>
            <valueField>ServiceContract.NOW__c</valueField>
        </filterItems>
        <filterItems>
            <field>ServiceContract.EndDate</field>
            <operation>greaterOrEqual</operation>
            <valueField>ServiceContract.NOW__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Site_Contact__c.field-meta.xml
<CustomField>
    <fullName>Site_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases Site Contact</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tech_Email_to_Case__c.field-meta.xml
<CustomField>
    <fullName>Tech_Email_to_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email to Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>List of values:
HMI&#39;s .
Networks .
PLC - Mitsubishi .
PLC - Other .
PLC - Pilz .
PLC - Rockwell .
PLC - Schneider .
PLC - Siemens .
SCADA .
SERVO&#39;s .
Telemetry .
Other</inlineHelpText>
    <label>Work Type</label>
    <referenceTo>WorkType</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Finance Contact</fullName>
            </value>
            <value>
                <fullName>Contract Manager</fullName>
            </value>
            <value>
                <fullName>Service Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_log__c/Error_log__c.object-meta.xml
<CustomObject>
    <label>Error Logs</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Integration logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_log__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Error Logs</relationshipLabel>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Service Contracts</relationshipLabel>
    <relationshipName>Service_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseEmailHandler.cls
global class CaseEmailHandler implements Messaging.InboundEmailHandler{
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {

        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();

        if(email.subject.contains(System.Label.Case_Email_Subject_CL)){

            List<String> emailBodyParts = email.htmlBody.split('<br>');
            String emailBody = email.htmlBody;
            System.debug('****emailBody:'+emailBody);
            String emailHtmlBody = emailBodyParts.get(0).stripHtmlTags();
            System.debug('****NOHTMLL:'+emailHtmlBody);
            parseEmailBody(emailHtmlBody);
        }
        return result;
    }

    public static void parseEmailBody(String emailHtmlBody){
        List<String> caseDetails = emailHtmlBody.split(',');
        String serviceTerritory = caseDetails.get(0).substring(caseDetails.get(0).indexOf(' '),caseDetails.get(0).length()).trim();
        System.debug('****serviceTerriotry:'+serviceTerritory+'*****');
        String contactName = caseDetails.get(1).trim();
        System.debug('****contactName:'+contactName+'*****');
        String accountName = caseDetails.get(2).trim();
        System.debug('****accountName:'+accountName+'*****');
        String phoneNo = caseDetails.get(3).trim();
        System.debug('****phoneNo:'+phoneNo+'*****');
        String street = caseDetails.get(4).trim();
        System.debug('****street:'+street+'*****');
        String suburb = caseDetails.get(5).trim().remove('&nbsp;');
        System.debug('****suburb:'+suburb+'*****');
        String postcode = caseDetails.get(6).trim();
        System.debug('****postcode:'+postcode+'*****');
        List<String> caseSubject = caseDetails.get(7).trim().split('<br>');
        System.debug('****caseSubject:'+caseSubject+'*****');

        
        createNewCase(emailHtmlBody, serviceTerritory, contactName, accountName, phoneNo, street, suburb, postcode, caseSubject.get(0));

    }

    public static void createNewCase(String emailBody, String serviceTerritory, String contactName, String accountName, String phoneNo, String street, String suburb, String postcode, String caseSubject){
        try{
            //Create case
            Case newCase = new Case();
            newCase.Subject = caseSubject;
            newCase.Description = caseSubject;
            newCase.Origin = 'Email';
            newCase.Tech_Email_to_Case__c = true;
            List<WorkType> otherType = WorkTypeDAO.getWorkTypeByName('Other');
            newCase.Work_Type__c = otherType.size() > 0 ? otherType.get(0).Id : null;
            //Find the Service Contract from the address
            List<ServiceContract> serviceContracts = ServiceContractDAO.getContractByAddress(street.toLowerCase(),suburb.toLowerCase(),postcode,serviceTerritory);
            
            //If Service Contract Found
            if(serviceContracts.size() > 0){
                //Link the case to the Service Contract
                newCase.Service_Contract__c = serviceContracts.get(0).Id;
                newcase.AccountId = serviceContracts.get(0).AccountId;

                System.debug('*****serviceContracts:'+serviceContracts);
                //Link the case to the Service Contract's contact and match the phone number
                List<Contact> contacts = new List<Contact>();
                if(Test.isRunningTest()){
                    contacts = ContactDAO.getContactsByPhone(phoneNo);
                }else{
                    List<List<SObject>> searchList = [FIND :phoneNo IN PHONE FIELDS RETURNING Contact(Id,AccountId)];
                    contacts = (List<Contact>)searchList.get(0);
                }
                System.debug('*****contacts:'+contacts);
                if(contacts.size() > 0 && contacts.get(0).AccountId == serviceContracts.get(0).AccountId){
                    newcase.ContactId = contacts.get(0).Id;
                    
                }else{
                    Contact newContact = phoneNo.startsWith('04') ? (new Contact(AccountId = serviceContracts.get(0).AccountId, LastName = contactName, MobilePhone = phoneNo, Contact_Type__c = 'Service Contact' )) : (new Contact(AccountId = serviceContracts.get(0).AccountId, LastName = contactName, Phone = phoneNo, Contact_Type__c = 'Service Contact' ));
                    insert newContact;
                    newcase.ContactId = newContact.Id;
                }
                //Link the case to the Service Contract's Service Territory
                newcase.Service_Territory__c = serviceContracts.get(0).Service_Territory__c;
                populateSiteContact(newcase, serviceContracts.get(0));

            }
            //If Service Contract Not Found
            else{
                //Find the contact with the same phone number
                List<Contact> contacts = new List<Contact>();
                if(Test.isRunningTest()){
                    contacts = ContactDAO.getContactsByPhone(phoneNo);
                }else{
                    List<List<SObject>> searchList = [FIND :phoneNo IN PHONE FIELDS RETURNING Contact(Id,AccountId)];
                    contacts = (List<Contact>)searchList.get(0);
                }
                
                //If contact Found
                if(contacts.size() > 0){
                    //Link the case to the contact
                    newcase.ContactId = contacts.get(0).Id;
                    //Link the case to the contacts account
                    newcase.AccountId = contacts.get(0).AccountId;
                    //Link the Bronze Service Contract to the case
                    serviceContracts = ServiceContractDAO.getContractByType(Constants.TYPE_BRONZE,Constants.SCO_TemplateContract_RT,serviceTerritory);
                    System.debug('****serviceContracts:'+serviceContracts);
                    if(serviceContracts.size() > 0){
                        newcase.Service_Contract__c = serviceContracts.get(0).Id;
                        populateSiteContact(newcase, serviceContracts.get(0));
                    }else{
                        newcase.Site_Contact__c = newcase.ContactId;
                    }
                }
                //If contact not found
                else{
                    //Find the account with the same name
                    System.debug('ACC:'+accountName.toLowerCase());
                    List<Account> accounts = AccountDAO.getAccountByName(accountName.toLowerCase());
                    System.debug('accounts:'+accounts);                    
                    //If account found
                    if(accounts.size() > 0){
                        //Link case to the account
                        newcase.AccountId = accounts.get(0).Id;
                        //Create contact and link to the account and case
                        Contact newContact = phoneNo.startsWith('04') ? (new Contact(AccountId = newCase.AccountId, LastName = contactName, MobilePhone = phoneNo, Contact_Type__c = 'Service Contact' )) : (new Contact(AccountId = newCase.AccountId, LastName = contactName, Phone = phoneNo, Contact_Type__c = 'Service Contact' ));
                        insert newContact;
                        newCase.ContactId = newContact.Id;
                        //Find the Bronze Service Contract to the Account
                        serviceContracts = ServiceContractDAO.getContractByAccountAndType(newcase.AccountId,Constants.TYPE_BRONZE);
                        //Is Service Contract is Found
                        if(serviceContracts.size() > 0){
                            newcase.Service_Contract__c = serviceContracts.get(0).Id;
                            populateSiteContact(newcase, serviceContracts.get(0));
                        }
                        //Is Service Contract is not found
                        else{
                            //Find the service contract with the record type 'Template Contract' for the service territory
                            serviceContracts = ServiceContractDAO.getContractByType(Constants.TYPE_BRONZE,Constants.SCO_TemplateContract_RT,serviceTerritory);
                            System.debug('****serviceContracts:'+serviceContracts);
                            if(serviceContracts.size() > 0){
                                newcase.Service_Contract__c = serviceContracts.get(0).Id;
                                populateSiteContact(newcase, serviceContracts.get(0));
                            }else{
                                newcase.Site_Contact__c = newcase.ContactId;
                            }
                        }
                    }
                    //If account not Found
                    else{
                        //Find Parent Cash Account for the State
                        List<Account> customers = AccountDAO.getCaseAccountByTerritory(serviceTerritory);
                        //Create cash account
                        Account cashAccount = new Account(Name = accountName, RecordTypeId = Utilities.getAccountRecordType('Cash Account'), ParentId = (customers.size() > 0 ? customers.get(0).Id: null), Site_Street__c = street, Site_City_Suburb__c = suburb, Site_Postcode__c = postcode, Site_State__c = serviceTerritory, Customer_Status__c = 'Pending');
                        insert cashAccount;
                        //Link case to the cash account
                        newCase.AccountId = cashAccount.Id;
                        //Create contact and link to the account and case
                        Contact newContact = phoneNo.startsWith('04') ? (new Contact(AccountId = cashAccount.Id, LastName = contactName, MobilePhone = phoneNo, Contact_Type__c = 'Service Contact' )) : (new Contact(AccountId = cashAccount.Id, LastName = contactName, Phone = phoneNo, Contact_Type__c = 'Service Contact' ));
                        insert newContact;
                        newCase.ContactId = newContact.Id;
                        //Link the Bronze Service Contract to the case
                        //Find the service contract with the record type 'Template Contract' for the service territory
                        serviceContracts = ServiceContractDAO.getContractByType(Constants.TYPE_BRONZE,Constants.SCO_TemplateContract_RT,serviceTerritory);
                        System.debug('****serviceContracts:'+serviceContracts);
                        if(serviceContracts.size() > 0){
                            newcase.Service_Contract__c = serviceContracts.get(0).Id;
                            populateSiteContact(newcase, serviceContracts.get(0));
                        }else{
                            newcase.Site_Contact__c = newcase.ContactId;
                        }
                    }
                }
            }
            System.debug('****newCase:'+newCase);
            insert newCase;
        }catch(Exception ex){
            System.debug('**Exception:'+ex.getMessage());
            Utilities.logError(emailBody, ex, Schema.SObjectType.Error_Log__c.getRecordTypeInfosByDeveloperName().get(Constants.ERR_DEV_Case_RT).getRecordTypeId());
        }
        
    }

    public static void populateSiteContact(Case newCase, ServiceContract serviceContract){
        if(serviceContract.RecordType.Name == Constants.SCO_TemplateContract_RT){
            newcase.Site_Contact__c = newcase.ContactId;
        }else{
            newcase.Site_Contact__c = serviceContract.ContactId;
        }
    }

}