force-app/main/default/objects/Account/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>N</fullName>
                <label>No supply</label>
            </value>
            <value>
                <fullName>L</fullName>
                <label>Legal Action</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Integration Pending</fullName>
            </value>
            <value>
                <fullName>Incomplete Information</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
                <default>true</default>
                <label>Not Applicable</label>
            </value>
            <value>
                <fullName>Waiting Confirmation</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
            <value>
                <fullName>Success</fullName>
                <isActive>false</isActive>
                <label>Success</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_With_Pronto__c.field-meta.xml
<CustomField>
    <fullName>Sync_With_Pronto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updating Pronto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company_Account_RT.recordType-meta.xml
<RecordType>
    <fullName>Company_Account_RT</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partnership_Account_RT.recordType-meta.xml
<RecordType>
    <fullName>Partnership_Account_RT</fullName>
    <active>true</active>
    <label>Partnership</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Sole_Trader_Account_RT.recordType-meta.xml
<RecordType>
    <fullName>Sole_Trader_Account_RT</fullName>
    <active>true</active>
    <label>Sole Trader</label>
</RecordType>

force-app/main/default/classes/AccountTriggerHandler.cls
/**
* 
@author: Cyrille Jeufo - Proquest Consulting
@initial version: 18/11/2019 - Initial version - Logic determines whether to make a callout or not
Cyrille Jeufo 	- 20/11/2019 -   added method to queue job from after trigger
* 
*/
public class AccountTriggerHandler {
    private static String companyRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName ().get('Company_Account_RT').getRecordTypeId();
    private static String soleTraderRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName ().get('Sole_Trader_Account_RT').getRecordTypeId();
    private static String partnershipRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName ().get('Partnership_Account_RT').getRecordTypeId();
    
    public static void checkAccountTriggerPoints(List<Account> newAccounts , Map<Id , Account> oldAccountMap){
        
        //check that we have some trigger points
        if(String.isNotBlank(Utilities.CUSTOMER_TRIGGER_POINTS)){ 
            
            //This list will be used to store all field that can cause trigger Salesforce => Pronto callout
            Set<String> triggerPoints = new Set<String>();
            if(Utilities.CUSTOMER_TRIGGER_POINTS.Trim().containsIgnoreCase(',')){
                for(String value : Utilities.CUSTOMER_TRIGGER_POINTS.trim().split(',')){
                    triggerPoints.add(value.trim());
                }
            }else{
                triggerPoints.add(Utilities.CUSTOMER_TRIGGER_POINTS.trim());
            }
            
            System.debug('&&&&Trigger points ' + triggerPoints);
            
            //Manual run from the 'Update Pronto' button
            //Or from Batch job
            for(Account acc : newAccounts){ 
                 if(!checkRecursive.SetOfIDs.contains(acc.Id)){
                     //if customer status pending abort
                     if(acc.Customer_Status__c == Utilities.CUSTOMER_STATUS_PENDING) 
                     {
                         acc.Sync_With_Pronto__c = false;
                         acc.Integration_Status__c = Utilities.INTEGRATION_DENIED;
                         continue;
                     }
                    
                     
                    if(acc.Sync_With_Pronto__c == true){
                        acc.Integration_Status__c = Utilities.INTEGRATION_PENDING;
                        continue;
                    }
                     
                    //only Company/Partnership/Sole Trader recordTypes
                    if(acc.RecordTypeId == companyRecordTypeId || acc.RecordTypeId == soleTraderRecordTypeId || acc.RecordTypeId == partnershipRecordTypeId )
                    {
                        for (Schema.SObjectField accField : Schema.SObjectType.Account.fields.getMap().values()) {
                            Schema.DescribeFieldResult describeResult = accField.getDescribe();
                            
                            //for each record look for the trigger point
                            if(triggerPoints.contains(describeResult.getName().trim())){
                                    //for updates we check if any change took place
                                    if(Trigger.isUpdate){
                                        Account oldAccount = (Account) oldAccountMap.get(acc.Id);
                                        if(oldAccount.get(describeResult.getName())  != acc.get(describeResult.getName())){
                                            acc.Sync_With_Pronto__c = true;
                                            System.debug('&&&&Trigger points 2');
                                        }
                                    }
                                //A trigger point was set during record creation
                                if(Trigger.isInsert && acc.get(describeResult.getName()) != null){
                                    acc.Sync_With_Pronto__c = true;
                                    acc.Integration_Status__c = Utilities.INTEGRATION_PENDING;
                                }
                                
                                
                            }
                        }
                    }
                     checkRecursive.SetOfIDs.add(acc.Id);
                 }
            }
            
        }
    }
    
    /**
    * Method to enqueue jobs whenever Sync_With_Pronto__c flag is to true
    * 
    */
    public static void syncWithPronto(List<Account> newAccounts , Map<Id , Account> newAccountMap){
        for(Account acc : newAccounts){
            if(acc.Sync_With_Pronto__c == true){
                if(Limits.getQueueableJobs() == Limits.getLimitQueueableJobs()) continue;
                SynchWithPronto syncjob = new SynchWithPronto(acc , 'Account');
                ID jobID = System.enqueueJob(syncjob);
            }
        }
    }
}