force-app/main/default/objects/Account/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Integration Pending</fullName>
            </value>
            <value>
                <fullName>Incomplete Information</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
                <default>true</default>
                <label>Not Applicable</label>
            </value>
            <value>
                <fullName>Waiting Confirmation</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
            <value>
                <fullName>Success</fullName>
                <isActive>false</isActive>
                <label>Success</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_With_Pronto__c.field-meta.xml
<CustomField>
    <fullName>Sync_With_Pronto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updating Pronto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Error_log__c/Error_log__c.object-meta.xml
<CustomObject>
    <label>Error Logs</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Integration logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_log__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Error Logs</relationshipLabel>
    <relationshipName>Error_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_log__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Error Logs</relationshipLabel>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_log__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipName>Integration_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_log__c/fields/workOrderLineItem__c.field-meta.xml
<CustomField>
    <fullName>workOrderLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order Line Item</label>
    <referenceTo>WorkOrderLineItem</referenceTo>
    <relationshipLabel>Error Logs</relationshipLabel>
    <relationshipName>Error_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_log__c/recordTypes/Account_ErrorLog_RT.recordType-meta.xml
<RecordType>
    <fullName>Account_ErrorLog_RT</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Error_log__c/recordTypes/SalesOrder_ErrorLog_RT.recordType-meta.xml
<RecordType>
    <fullName>SalesOrder_ErrorLog_RT</fullName>
    <active>true</active>
    <label>SalesOrder</label>
</RecordType>

force-app/main/default/objects/Error_log__c/recordTypes/Transaction_ErrorLog_RT.recordType-meta.xml
<RecordType>
    <fullName>Transaction_ErrorLog_RT</fullName>
    <active>true</active>
    <label>Transaction</label>
</RecordType>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-1{0000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Sync_With_Pronto__c.field-meta.xml
<CustomField>
    <fullName>Sync_With_Pronto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updating Pronto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>This object will be used to create records for the purpose of invoicing</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Sync_With_Pronto__c.field-meta.xml
<CustomField>
    <fullName>Sync_With_Pronto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updating Pronto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/recordTypes/WorkOrder_SalesOrder_RT.recordType-meta.xml
<RecordType>
    <fullName>WorkOrder_SalesOrder_RT</fullName>
    <active>true</active>
    <label>Work Order</label>
</RecordType>

force-app/main/default/objects/WorkOrderLineItem/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Send_Timesheet__c.field-meta.xml
<CustomField>
    <fullName>Send_Timesheet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Timesheet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Sync_With_Pronto__c.field-meta.xml
<CustomField>
    <fullName>Sync_With_Pronto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updating Pronto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Integration_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Integration Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Payroll Period Validated</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Successful</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
        <isActive>false</isActive>
        <label>None</label>
    </customValue>
    <masterLabel>Integration Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SyncWithProntoBatch.cls
/**
* 
@author: Cyrille Jeufo - Proquest Consulting
@description: This class retrieves all records matching a query passed from SyncWithProntoJob and
			  set Sync_With_Pronto__c to true so that the relevant trigger starts the integration
* 
*/
global class SyncWithProntoBatch implements Database.Batchable<sObject> , Database.AllowsCallouts , Database.Stateful{
    global final String Query;
    public String customer_recordtype = Schema.SObjectType.Error_log__c.getRecordTypeInfosByDeveloperName ().get('Account_ErrorLog_RT').getRecordTypeId();
    public String transaction_recordtype = Schema.SObjectType.Error_log__c.getRecordTypeInfosByDeveloperName ().get('Transaction_ErrorLog_RT').getRecordTypeId();
    private static String salesOrderRecordtypeId = Schema.SObjectType.Sales_Order__c.getRecordTypeInfosByDeveloperName ().get('WorkOrder_SalesOrder_RT').getRecordTypeId();
    public static String so_recordtype = Schema.SObjectType.Error_log__c.getRecordTypeInfosByDeveloperName ().get('SalesOrder_ErrorLog_RT').getRecordTypeId();

    public Set<String> processed = new Set<String>();
    public List<Account> accounts = new List<Account>();
    public List<WorkOrderLineItem> wolis = new List<WorkOrderLineItem>();
    public List<Sales_Order__c> salesOrders = new List<Sales_Order__c>();
    
    
    public List<Error_log__c> logs = new List<Error_log__c>();
    public Set<Id> logAlreadyCreated = new Set<Id>();
    global SyncWithProntoBatch(String queryIn){
        Query = queryIn;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, 
                        List<sObject> scope){

        for(Sobject obj : scope){
            //accounts
            if(obj.getSObjectType().getDescribe().getName() == 'Account'){
                Account acc = (Account)obj;
                if(processed.contains(acc.Id)) continue;
                acc.Sync_With_Pronto__c = true;
                acc.Integration_Status__c = Utilities.INTEGRATION_PENDING;
                accounts.add(acc);
                processed.add(acc.Id);
            }else if(obj.getSObjectType().getDescribe().getName() == 'WorkOrderLineItem'){
                WorkOrderLineItem woli = (WorkOrderLineItem)obj;
                if(processed.contains(woli.Id)) continue;

                woli.Sync_With_Pronto__c = true;
                woli.Integration_Status__c = Utilities.INTEGRATION_PENDING;
                woli.Send_Timesheet__c = false;
                
                SynchWithPronto syncjob = new SynchWithPronto(woli , 'WorkOrderLineItem', true);
                ID jobID = System.enqueueJob(syncjob);

                processed.add(woli.Id);
            }else if(obj.getSObjectType().getDescribe().getName() == 'Sales_Order__c'){
                Sales_Order__c so = (Sales_Order__c)obj;
                //do not sync if created from work order or already synced
                if(processed.contains(so.Id)) continue;
                SynchWithPronto syncjob = new SynchWithPronto(so , 'SalesOrder');
                ID jobID = System.enqueueJob(syncjob);
                processed.add(so.Id);
            }else if(obj.getSObjectType().getDescribe().getName() == 'Purchase_Order__c'){
                Purchase_Order__c po = (Purchase_Order__c)obj;
                if(processed.contains(po.Id)) continue;
                SynchWithPronto syncjob = new SynchWithPronto(po , 'PurchaseOrder');
                ID jobID = System.enqueueJob(syncjob);
                processed.add(po.Id);
            }
        }
                            
        System.debug('$$$accounts size ' + accounts.size());
        if(accounts.size() > 0) {
            List<Database.SaveResult> result = Database.update(accounts , false);  
            // Iterate through each returned result
            System.debug('@@@ accounts result ' + result );
            for (Database.SaveResult sr : result) {
                for (Integer i = 0; i < accounts.size(); i++) {
                	if (!sr.isSuccess() && !logAlreadyCreated.contains(accounts[i].Id)) {
                        for(Database.Error err : sr.getErrors()){
                            Error_log__c logRecord = new Error_log__c(Customer__c = accounts[i].Id , Message__c	=   err.message, recordTypeId = customer_recordtype, Subject__c = String.valueOf(err.statusCode));
                            logs.add(logRecord);
                        }
                        logAlreadyCreated.add(accounts[i].Id);
                    }
                }
            }
        }
        
        // System.debug('$$$wolis ' + wolis);
        // System.debug('$$$wolis size ' + wolis.size());
        // if(wolis.size() > 0) {
        //     List<Database.SaveResult> result = Database.update(wolis , false) ;  
        //     // Iterate through each returned result
        //     System.debug('@@@wolis result ' + result );
        //     for (Database.SaveResult sr : result) {
        //         for (Integer i = 0; i < wolis.size(); i++) {
        //         	if (!sr.isSuccess() && !logAlreadyCreated.contains(wolis[i].Id)) {
        //                 for(Database.Error err : sr.getErrors()){
        //                     Error_log__c logRecord = new Error_log__c(workOrderLineItem__c = wolis[i].Id, Message__c	=   err.message, recordTypeId = transaction_recordtype, Subject__c = String.valueOf(err.statusCode));
        //                     logs.add(logRecord);
        //                 }
        //                 logAlreadyCreated.add(wolis[i].Id);
        //             }
        //         }
        //     }
        // }
                            
    }
    
    global void finish(Database.BatchableContext BC){
        if(logs.size() > 0) Database.insert(logs , false) ;  
    }
    
}