force-app/main/default/objects/Purchase_Order_Line_Item__c/Purchase_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <displayFormat>POLI-{00000000}</displayFormat>
        <label>Purchase Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/PurchaseOrderLineItemTriggerHandler.cls
public class PurchaseOrderLineItemTriggerHandler {
    // public static void calculateActualHours(List<Purchase_Order_Line_Item__c> newPOLI , Map<Id , Purchase_Order_Line_Item__c> oldPOLIMap){
    //     for(Purchase_Order_Line_Item__c po : newPOLI){
    //         Purchase_Order_Line_Item__c oldPo = oldPOLIMap != null ? ((Purchase_Order_Line_Item__c) oldPOLIMap.get(po.Id)) : null;
    //         if((oldPo != null && (po.Start_Date_Time__c != oldPo.Start_Date_Time__c || po.End_Date_Time__c != oldPo.End_Date_Time__c)) ||
    //          (oldPo == null && po.Start_Date_Time__c != null && po.End_Date_Time__c != null)){
    //             po.Quantity__c = Utilities.getActualHours(po.Start_Date_Time__c, po.End_Date_Time__c);
    //         }
    //     }
    // }
}