force-app/main/default/objects/User/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Line_of_Business_Code__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business_Code__c</fullName>
    <label>Line of Business Code</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserDAO.cls
public class UserDAO {
    public static Map<Id,User> getUsers(Set<Id> usersIds) {
        return new Map<Id,User>([   Select  Id,
                                            Line_of_Business_Code__c,
                                            EmployeeNumber,
                                 			Company_Code__c
                                    From    User
                                    Where   ID IN :usersIds]);
    }
}