force-app/main/default/objects/PricebookEntry/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <formula>TEXT(Product2.Contract_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <formula>TEXT(Product2.Resource_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Service_Time__c.field-meta.xml
<CustomField>
    <fullName>Service_Time__c</fullName>
    <formula>TEXT(Product2.Service_Time__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Usage_per_hour__c.field-meta.xml
<CustomField>
    <fullName>Usage_per_hour__c</fullName>
    <label>Usage per hour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PricebookEntryDAO.cls
public class PricebookEntryDAO {

    public static  List<PricebookEntry> getEntriesUsingPricebookIds(Set<id> pricebookIds){
        List<PricebookEntry> entries = [SELECT id, 
                                               Resource_Type__c, 
                                               Contract_Type__c, 
                                               Service_Time__c,
                                               UnitPrice,
                                               Usage_per_hour__c 
                                        FROM   PricebookEntry 
                                        WHERE  Pricebook2Id 
                                        IN     :pricebookIds];

        return entries;
        
    }
}