force-app/main/default/objects/ServiceContract/fields/Normal_Time__c.field-meta.xml
<CustomField>
    <fullName>Normal_Time__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Normal Time</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Service_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Pronto_Contract_No__c.field-meta.xml
<CustomField>
    <fullName>Pronto_Contract_No__c</fullName>
    <externalId>true</externalId>
    <label>Pronto Contract No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Service Contracts</relationshipLabel>
    <relationshipName>Service_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Shipping_City_Lower__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City_Lower__c</fullName>
    <formula>LOWER( ShippingCity )</formula>
    <label>Shipping City Lower</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Shipping_Street_Lower__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Street_Lower__c</fullName>
    <formula>LOWER( ShippingStreet )</formula>
    <label>Shipping Street Lower</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/Business_Hours__c.field-meta.xml
<CustomField>
    <fullName>Business_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Hours</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Service_Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Contract_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bronze Support</fullName>
    </customValue>
    <customValue>
        <fullName>Silver Support</fullName>
    </customValue>
    <customValue>
        <fullName>Gold Support</fullName>
    </customValue>
    <customValue>
        <fullName>Platinum Support</fullName>
    </customValue>
    <masterLabel>Contract Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ServiceContractDAO.cls
public class ServiceContractDAO {
    public static  List<ServiceContract> getContractByAddress(String street, String suburb, String postcode, String serviceTerritory){
        List<ServiceContract> scs = [   Select  Id, 
                                                ShippingStreet, 
                                                ShippingCity, 
                                                ShippingPostalCode, 
                                                AccountId, 
                                                ContactId, 
                                                Service_Territory__c,
                                                RecordType.Name 
                                        From    ServiceContract 
                                        Where   Shipping_Street_Lower__c = :street 
                                        AND     Shipping_City_Lower__c = :suburb 
                                        AND     ShippingPostalCode = :postcode 
                                        AND     Service_Territory__r.Name  = :serviceTerritory];

        return scs;
        
    }

    public static  List<ServiceContract> getContractByType(String type, String recType, String serviceTerritory){
        List<ServiceContract> scs = [   Select  Id,
                                                RecordType.Name,
                                                ContactId
                                        From    ServiceContract 
                                        Where   Type__c = :type 
                                        AND     RecordType.Name = :recType 
                                        AND     Service_Territory__r.Name = :serviceTerritory];

        return scs;
        
    }

    public static List<ServiceContract> getContractByAccountAndType(Id AccountId, String type){
        List<ServiceContract> scs = [   Select  Id, 
                                                RecordType.Name,
                                                ContactId 
                                        From    ServiceContract 
                                        Where   AccountId = :AccountId 
                                        AND     Type__c = :type];
        return scs;
    }

    public static List<ServiceContract> getContractByContactIds(Set<Id> contactIds){
        List<ServiceContract> scs = [   Select  Id, 
                                                RecordType.Name,
                                                Name,
                                                ContactId,
                                                Normal_Time__c 
                                        From    ServiceContract 
                                        Where   ContactId IN :contactIds
                                        And     Status = 'Active'];
        return scs;
    }

    public static List<ServiceContract> getContractByProntoCode(String contCode){
        List<ServiceContract> scs = [   Select  Id,
                                                Service_Territory__c 
                                        From    ServiceContract
                                        Where   Pronto_Contract_No__c = :contCode];
        return scs;
    }

    public static List<ServiceContract> getContractByContractIds(Set<Id> contractIds){
        List<ServiceContract> scs = [   Select  Id, 
                                                RecordType.Name,
                                                Name,
                                                ContactId,
                                                Normal_Time__c,
                                                Service_Territory__r.Business_Hours__c 
                                        From    ServiceContract 
                                        Where   Id IN :contractIds];
        return scs;
    }
}