force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-1{0000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Sync_With_Pronto__c.field-meta.xml
<CustomField>
    <fullName>Sync_With_Pronto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updating Pronto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>WorkOrder.Status</field>
            <operation>notEqual</operation>
            <value>Completed, Awaiting Customer PO, Ready To Invoice</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Work_Order_Completed__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Completed__c</fullName>
    <label>Work Order Completed?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Sync_With_Pronto__c.field-meta.xml
<CustomField>
    <fullName>Sync_With_Pronto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updating Pronto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Within_Current_Payroll_Period__c.field-meta.xml
<CustomField>
    <fullName>Within_Current_Payroll_Period__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this transaction was validated against Payroll</description>
    <label>Within Current Payroll Period</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Integration_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Integration Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Payroll Period Validated</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Successful</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
        <isActive>false</isActive>
        <label>None</label>
    </customValue>
    <masterLabel>Integration Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ServiceAppointmentTriggerHandler.cls
public class ServiceAppointmentTriggerHandler {

    public static void  saValidationforCompleteWO (List<ServiceAppointment> newServiceAppointments , Map<Id , ServiceAppointment> oldServiceAppointmentsMap){
        Set<Id> workOrderIds = new Set<Id>();
        for(ServiceAppointment sa: newServiceAppointments){
            ServiceAppointment oldSa = (ServiceAppointment) oldServiceAppointmentsMap.get(sa.Id);
            if(sa.Work_Order_Completed__c == 'Yes' && sa.Status != oldSa.Status && (sa.Status == Constants.SERVICE_APPOINMENT_STATUS_COMPLETE || sa.Status == Constants.SERVICE_APPOINMENT_STATUS_CANNOT_COMPLETE)){
                workOrderIds.add(sa.Work_Order__c);
            }    
        }

        if(workOrderIds.size() > 0){
            
            Map <Id, String> woToSANumberMap = new Map <Id, String>();
            
            List<ServiceAppointment> openSAs = ServiceAppointmentDAO.getOpenServiceAppointments(workOrderIds);            
            for(ServiceAppointment sa :openSAs){
                for(ServiceAppointment satrigger :newServiceAppointments){
                    if(satrigger.AppointmentNumber <> sa.AppointmentNumber){
                        woToSANumberMap.put(sa.ParentRecordId, sa.AppointmentNumber);
                    }
                }
            }
            
            for(ServiceAppointment sa: newServiceAppointments){
                if(woToSANumberMap.get(sa.ParentRecordId)<>NULL){
                    sa.addError('You cannot Complete the work order as other Service Appointments are still opened: ' +woToSANumberMap.get(sa.ParentRecordId));
                }
            }
        }
    }
    
    public static void  saValidationForOpenPOs (List<ServiceAppointment> newServiceAppointments , Map<Id , ServiceAppointment> oldServiceAppointmentsMap){
        Set<Id> workOrderIds = new Set<Id>();
        for(ServiceAppointment sa: newServiceAppointments){
            ServiceAppointment oldSa = (ServiceAppointment) oldServiceAppointmentsMap.get(sa.Id);
            if(sa.Work_Order_Completed__c == 'Yes' && sa.Status != oldSa.Status && (sa.Status == Constants.SERVICE_APPOINMENT_STATUS_COMPLETE || sa.Status == Constants.SERVICE_APPOINMENT_STATUS_CANNOT_COMPLETE)){
                workOrderIds.add(sa.Work_Order__c);
            }    
        }

        if(workOrderIds.size() > 0){
            
            Map <Id, String> woToPONumberMap = new Map <Id, String>();
            
            List<Purchase_Order__c> openPOs = PurchaseOrderDAO.getOpenPOs(workOrderIds);    
            if(openPOs.size()>0){        
                for(Purchase_Order__c po :openPOs){
                    for(ServiceAppointment satrigger :newServiceAppointments){
                        if(satrigger.ParentRecordId == po.Work_Order__c){
                            woToPONumberMap.put(satrigger.ParentRecordId, po.Name);
                        }
                    }
                }
            
            }
            
            for(ServiceAppointment sa: newServiceAppointments){
                if(woToPONumberMap.get(sa.ParentRecordId)<>NULL){
                    sa.addError('You cannot Complete the work order as some Purchase Orders are still opened: ' +woToPONumberMap.get(sa.ParentRecordId));
                }
            }
        }
    }
    
    //reset Actual Start Time seconds to 0 
    public static void  updateActualStartTime(List<ServiceAppointment> newServiceAppointments){
        
        for(ServiceAppointment sa:newServiceAppointments)
            { 
                if(sa.ActualStartTime!=null)
                {
                  sa.ActualStartTime = Utilities.DatetimeZeroSecond(sa.ActualStartTime);
                }
            }
        }

    //check if SA should be synced and if any exist then send the timesheet to Pronto
    public static void  syncWithProntoForCompletion(List<ServiceAppointment> newServiceAppointments , Map<Id , ServiceAppointment> oldServiceAppointmentsMap){
        Set<Id> workOrderIds = new Set<Id>();
        for(ServiceAppointment sa: newServiceAppointments){
            ServiceAppointment oldSa = (ServiceAppointment) oldServiceAppointmentsMap.get(sa.Id);
            if(sa.Status != oldSa.Status && (sa.Status == Constants.SERVICE_APPOINMENT_STATUS_COMPLETE || sa.Status == Constants.SERVICE_APPOINMENT_STATUS_CANNOT_COMPLETE)){
                workOrderIds.add(sa.Work_Order__c);
            }    
        }

        if(workOrderIds.size() > 0){
            Map<Id,WorkOrderLineItem> workOrderLineItems = WorkOrderLineItemDAO.getWorkOrderLineItemsUsingWoIds(workOrderIds);
            
            // Boolean checkValidTransactionExist = false;
            // //Check atleast one transaction exist withing the current payroll period
            // for(WorkOrderLineItem woli :workOrderLineItems.values()){
            //     if(woli.Within_Current_Payroll_Period__c && woli.Integration_Status__c != Utilities.INTEGRATION_WAITING && woli.Integration_Status__c != Utilities.INTEGRATION_SUCCESSFUL){
            //         checkValidTransactionExist = true;
            //     }
            // }
            // if(checkValidTransactionExist){
            Map<Id,WorkOrderLineItem> itemsToSend = new Map<Id,WorkOrderLineItem>();
            
            for(WorkOrderLineItem woli :workOrderLineItems.values()){
                if( woli.Integration_Status__c != Utilities.INTEGRATION_WAITING && woli.Integration_Status__c != Utilities.INTEGRATION_SUCCESSFUL){
                    woli.Sync_With_Pronto__c = true;
                    system.debug('wwww'+woli.Id);
                    system.debug('wwww222'+woli);
                    itemsToSend.put(woli.Id,woli);
                    
                }
             }
            //Send the transaction to Pronto
             	WorkOrderLineItemHandler.syncWithPronto(itemsToSend, null, false);
                system.debug('send'+itemsToSend);
            }
        }
    

}