force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-1{0000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Account_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Code__c</fullName>
    <formula>Supplier__r.Pronto_Account_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>CreatedBy.Company_Code__c</formula>
    <label>Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Currency_Rate__c.field-meta.xml
<CustomField>
    <fullName>Currency_Rate__c</fullName>
    <label>Currency Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Delivery_Address_Name__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Address_Name__c</fullName>
    <label>Delivery Address Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Delivery_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Instructions__c</fullName>
    <label>Delivery Instructions</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Line_of_Business_Code__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business_Code__c</fullName>
    <formula>CreatedBy.Line_of_Business_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line of Business Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Postal_City__c.field-meta.xml
<CustomField>
    <fullName>Postal_City__c</fullName>
    <label>Postal City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Postal_Country__c.field-meta.xml
<CustomField>
    <fullName>Postal_Country__c</fullName>
    <label>Postal Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Postal_Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postal_Postcode__c</fullName>
    <label>Postal Postcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Postal_State__c.field-meta.xml
<CustomField>
    <fullName>Postal_State__c</fullName>
    <label>Postal State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Postal_Street__c.field-meta.xml
<CustomField>
    <fullName>Postal_Street__c</fullName>
    <label>Postal Street</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/SC_Project_Code__c.field-meta.xml
<CustomField>
    <fullName>SC_Project_Code__c</fullName>
    <label>Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MAT</fullName>
                <label>Materials</label>
            </value>
            <value>
                <fullName>SUB</fullName>
                <label>Subcontrator</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <formula>LastModifiedBy.Username</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Warehouse_Code__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Code__c</fullName>
    <label>Warehouse Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Warehouse</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>WorkOrder.Status</field>
            <operation>notEqual</operation>
            <value>Completed, Awaiting Customer PO, Ready To Invoice</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/Purchase_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <displayFormat>POLI-{00000000}</displayFormat>
        <label>Purchase Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Date_Expected__c.field-meta.xml
<CustomField>
    <fullName>Date_Expected__c</fullName>
    <label>Date Expected</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/POLI_Number__c.field-meta.xml
<CustomField>
    <fullName>POLI_Number__c</fullName>
    <formula>VALUE(RIGHT(Name, 5))</formula>
    <label>POLI Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Supplier_Code__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Code__c</fullName>
    <label>Supplier Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>12</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <label>Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Units</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Line_of_Business_Code__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business_Code__c</fullName>
    <label>Line of Business Code</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Units.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EACH</fullName>
        <label>Each</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>PACK OF 10</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
    </customValue>
    <customValue>
        <fullName>1000</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <label>Pack of 200</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>Pack of 25</label>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>500</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
        <label>Bag</label>
    </customValue>
    <customValue>
        <fullName>BOX</fullName>
        <label>1 Box</label>
    </customValue>
    <customValue>
        <fullName>BTLE</fullName>
        <label>Bottle</label>
    </customValue>
    <customValue>
        <fullName>BUCK</fullName>
        <label>Bucket</label>
    </customValue>
    <customValue>
        <fullName>CARD</fullName>
        <label>Card</label>
    </customValue>
    <customValue>
        <fullName>CART</fullName>
        <label>Cartridge</label>
    </customValue>
    <customValue>
        <fullName>COIL</fullName>
        <label>Coil</label>
    </customValue>
    <customValue>
        <fullName>COUT</fullName>
        <label>Callout</label>
    </customValue>
    <customValue>
        <fullName>CTN</fullName>
        <label>Carton</label>
    </customValue>
    <customValue>
        <fullName>DAY</fullName>
        <label>Day</label>
    </customValue>
    <customValue>
        <fullName>DRUM</fullName>
        <label>Drum</label>
    </customValue>
    <customValue>
        <fullName>HOUR</fullName>
        <label>Hour</label>
    </customValue>
    <customValue>
        <fullName>HRS</fullName>
        <label>Hours</label>
    </customValue>
    <customValue>
        <fullName>JAR</fullName>
        <label>Jar</label>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
        <label>Kilogram</label>
    </customValue>
    <customValue>
        <fullName>KIT</fullName>
        <label>Kit</label>
    </customValue>
    <customValue>
        <fullName>KM</fullName>
        <label>Kilometre</label>
    </customValue>
    <customValue>
        <fullName>LEN</fullName>
        <label>Length</label>
    </customValue>
    <customValue>
        <fullName>LOT</fullName>
        <label>Lot</label>
    </customValue>
    <customValue>
        <fullName>LTR</fullName>
        <label>Litre</label>
    </customValue>
    <customValue>
        <fullName>MM</fullName>
        <label>Millimetre</label>
    </customValue>
    <masterLabel>Units</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Warehouse.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BUR</fullName>
        <label>BUR - Burnie Warehouse</label>
    </customValue>
    <customValue>
        <fullName>CONS</fullName>
        <label>CONS - Consignment Stock</label>
    </customValue>
    <customValue>
        <fullName>DAN</fullName>
        <label>DAN - 2/491 Hammond Rd Dandenong Sth</label>
    </customValue>
    <customValue>
        <fullName>EMBE</fullName>
        <label>EMBE - Embedded Expertise</label>
    </customValue>
    <customValue>
        <fullName>HBT</fullName>
        <label>HBT - Hobart Warehouse</label>
    </customValue>
    <customValue>
        <fullName>KATH</fullName>
        <label>KATH - Katherine Warehouse</label>
    </customValue>
    <customValue>
        <fullName>KEYS</fullName>
        <label>KEYS - Keysborough Warehouse</label>
    </customValue>
    <customValue>
        <fullName>LST</fullName>
        <label>LST - Launceston Warehouse</label>
    </customValue>
    <customValue>
        <fullName>MAIN</fullName>
        <label>MAIN - Main Warehouse</label>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
        <label>NSW - North Ryde Warehouse</label>
    </customValue>
    <customValue>
        <fullName>NT</fullName>
        <label>NT - Northern Territory Warehouse</label>
    </customValue>
    <customValue>
        <fullName>NUKO</fullName>
        <label>NUKO - Nukon Company Warehouse</label>
    </customValue>
    <customValue>
        <fullName>QLD</fullName>
        <label>QLD - Electronics St Warehouse</label>
    </customValue>
    <customValue>
        <fullName>SKL</fullName>
        <label>SKL - Skills Lab Warehouse</label>
    </customValue>
    <customValue>
        <fullName>TONS</fullName>
        <label>TONS - Tonsley Warehouse</label>
    </customValue>
    <customValue>
        <fullName>VIC</fullName>
        <label>VIC - 2/216 Turner St Port Melbourne</label>
    </customValue>
    <customValue>
        <fullName>WA</fullName>
        <label>WA - Warehouse</label>
    </customValue>
    <customValue>
        <fullName>WHY</fullName>
        <label>WHY - Whyalla Warehouse</label>
    </customValue>
    <masterLabel>Warehouse</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PurchaseOrder.cls
/**
* 
@author: Imalka Fernando - Proquest Consulting
@description: classes wrapping Purchase order and Purchase Order line items
* 
*/
public class PurchaseOrder {

    public String id {get;set;} 
    public String work_order {get;set;} 
    public String sf_order_number {get;set;} 
    public String account_code {get;set;} 
    public String line_of_business_code {get;set;} 
    public String order_type {get; set;}
    public String order_date {get;set;} 
    public String arrival_date {get;set;} 
    public String delivery_instructions {get;set;} 
    public String warehouse {get;set;} 
    public String currency_code {get;set;} 
    public Double currency_rate {get;set;} 
    public String user {get;set;} 
    public String project_code {get;set;} 
    public String company {get;set;} 
    public String territory_company {get;set;} 
    public String postal_name {get;set;} 
    public String postal_street {get;set;} 
    public String postal_city {get;set;} 
    public String postal_state {get;set;} 
    public String postal_country {get;set;} 
    public String postal_postal_code {get;set;}
    public String notes {get;set;} 
    public List<PurchaseOrderItems> purchase_order_items {get;set;} 
    public Long timestamp {get;set;} 
    
    public class PurchaseOrderItems {
        public String id {get;set;} 
        public Integer salesforce_line_id {get;set;} 
        public String supplier_code {get;set;} 
        public Double qty {get;set;} 
        public Double price {get;set;} 
        public String measure {get;set;} 
        public Double tax_rate {get;set;} 
        public String date_expected {get;set;} 
        public String item_description {get;set;} 
    }
    
    public static PurchaseOrder WrappedPO(Purchase_Order__c poIn){
        PurchaseOrder poWrapped = new PurchaseOrder();
        
        poWrapped.id = poIn.Id;
        poWrapped.work_order = (poIn.Work_Order__c != null ? [SELECT WorkOrderNumber FROM WorkOrder WHERE ID =: poIn.Work_Order__c ].WorkOrderNumber : null);
        poWrapped.sf_order_number = poIn.Name;
        poWrapped.account_code = poIn.Account_Code__c;
        poWrapped.line_of_business_code = poIn.Line_of_Business_Code__c;
        poWrapped.order_type = poIn.Type__c;
        //date format: year/month/day
        poWrapped.order_date = (poIn.Order_Date__c != null ? string.valueOf(date.newinstance(poIn.Order_Date__c.year(), poIn.Order_Date__c.month(), poIn.Order_Date__c.day())) : null );
        poWrapped.arrival_date = (poIn.Due_Date__c != null ? string.valueOf(date.newinstance(poIn.Due_Date__c.year(), poIn.Due_Date__c.month(), poIn.Due_Date__c.day())) : null );
        poWrapped.delivery_instructions = poIn.Delivery_Instructions__c;
        
        poWrapped.warehouse = poIn.Warehouse_Code__c ;
        poWrapped.currency_code = poIn.Currency__c;
        poWrapped.currency_rate = poIn.Currency_Rate__c;
        poWrapped.user = poIn.User__c;
        poWrapped.project_code = poIn.SC_Project_Code__c;
        poWrapped.company = poIn.Company__c;
        poWrapped.territory_company = poIn.TECH_Work_Order_Territory_Branch_Code__c;
        poWrapped.postal_name = poIn.Delivery_Address_Name__c;
        poWrapped.postal_street = poIn.Postal_Street__c;
        poWrapped.postal_city = poIn.Postal_City__c;
        poWrapped.postal_state = poIn.Postal_State__c;
        poWrapped.postal_country = poIn.Postal_Country__c;
        poWrapped.postal_postal_code = poIn.Postal_Postcode__c;
        poWrapped.notes = poIn.Notes__c != null ? poIn.Notes__c.replaceAll('<br>','\n') : '';

        if(poIn.LastModifiedDate != null){
            poWrapped.timestamp = poIn.LastModifiedDate.getTime();
        }
        
        if(poIn.createdDate != null){
            poWrapped.timestamp = poIn.createdDate.getTime();
        }
        
        if(poWrapped.timestamp == null)
        {
            poWrapped.timestamp = System.now().getTime();
        }
        return poWrapped;
    }
    
    public static PurchaseOrderItems WrappedPOLI(Purchase_Order_Line_Item__c poliIn){
        PurchaseOrderItems poliWrapped = new PurchaseOrderItems();
        
        poliWrapped.id = poliIn.Id;
        poliWrapped.salesforce_line_id = Integer.valueOf(poliIn.POLI_Number__c);
        poliWrapped.supplier_code = poliIn.Supplier_Code__c;
        poliWrapped.qty = poliIn.Quantity__c;
        poliWrapped.price = poliIn.Cost__c;
        poliWrapped.measure = poliIn.Units__c;
        poliWrapped.tax_rate = poliIn.Tax_Rate__c;
        poliWrapped.date_expected = (poliIn.Date_Expected__c != null ? string.valueOf(date.newinstance(poliIn.Date_Expected__c.year(), poliIn.Date_Expected__c.month(), poliIn.Date_Expected__c.day())) : null );
        poliWrapped.item_description = poliIn.Description__c;

        return poliWrapped;
    }
}