force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-1{0000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Sync_With_Pronto__c.field-meta.xml
<CustomField>
    <fullName>Sync_With_Pronto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updating Pronto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Integration_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Integration Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Payroll Period Validated</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Successful</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
        <isActive>false</isActive>
        <label>None</label>
    </customValue>
    <masterLabel>Integration Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PurchaseOrderTriggerHandler.cls
public class PurchaseOrderTriggerHandler {
    //check if PO should be synced
    public static void checkTriggerPoints(List<Purchase_Order__c> newPurchaseOrders , Map<Id , Purchase_Order__c> oldPurchaseOrdersMap){
        for(Purchase_Order__c po : newPurchaseOrders){
                Purchase_Order__c oldPo = (Purchase_Order__c) oldPurchaseOrdersMap.get(po.Id);
                if(po.Sync_With_Pronto__c == true && oldPo.Sync_With_Pronto__c == false && (po.Integration_Status__c != Utilities.INTEGRATION_SUCCESSFUL && po.Integration_Status__c != Utilities.INTEGRATION_WAITING) && po.Status__c == Constants.PURCHASE_ORDER_STATUS_APPROVED){
                    po.Integration_Status__c = Utilities.INTEGRATION_PENDING;
                }else if(po.Status__c != oldPo.Status__c ){
                    if((po.Integration_Status__c != Utilities.INTEGRATION_SUCCESSFUL  && po.Integration_Status__c != Utilities.INTEGRATION_WAITING && po.Status__c == Constants.PURCHASE_ORDER_STATUS_APPROVED) ||
                        ((po.Integration_Status__c == Utilities.INTEGRATION_SUCCESSFUL || po.Integration_Status__c == Utilities.INTEGRATION_WAITING) && po.Status__c == Constants.PURCHASE_ORDER_STATUS_CANCELLED)){
                        po.Sync_With_Pronto__c = true;
                        po.Integration_Status__c = Utilities.INTEGRATION_PENDING;
                    }
                }else if(po.Sync_With_Pronto__c == true && oldPo.Sync_With_Pronto__c == false && po.Integration_Status__c == Utilities.INTEGRATION_SUCCESSFUL){
                    po.addError(System.Label.Record_Locked_CL);
                }else{
                    po.Sync_With_Pronto__c = false;
                }
        }
    }

    /**
    * synch with Pronto
    */
    public static void syncWithPronto(List<Purchase_Order__c> newPurchaseOrders){
        List<Purchase_Order__c> purchaseOrders = new List<Purchase_Order__c>();
        
        for(Purchase_Order__c po : newPurchaseOrders){
            if(po.Sync_With_Pronto__c == true ){
                if(Limits.getQueueableJobs() == Limits.getLimitQueueableJobs()) continue;
                SynchWithPronto syncjob = new SynchWithPronto(po , 'PurchaseOrder');
                ID jobID = System.enqueueJob(syncjob);
            }
        }
    }
}