force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-1{0000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>WorkOrder.Status</field>
            <operation>notEqual</operation>
            <value>Completed, Awaiting Customer PO, Ready To Invoice</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PurchaseOrderDAO.cls
public class PurchaseOrderDAO {
    
    public static  List<Purchase_Order__c> getOpenPOs(Set<id> woIds){
        List<Purchase_Order__c> pos = [SELECT  id, 
                                               Status__c, 
                                               Name, 
                                               Work_Order__c 
                                       FROM    Purchase_Order__c 
                                       WHERE   Work_Order__c 
                                       IN      :woIds 
                                       AND     Status__c = :Constants.PURCHASE_ORDER_STATUS_PENDING_APPROVED];

        return pos;
        
    }
}