force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-1{0000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Account_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Code__c</fullName>
    <formula>Supplier__r.Pronto_Account_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/PurchaseOrderCancel.cls
/**
* 
@author: Imalka Fernando - Proquest Consulting
@description: classes wrapping Purchase order for cancellation
* 
*/
public class PurchaseOrderCancel {
    public String id {get;set;} 
    public String external_order_number {get;set;} 
    public String cancellation_reason {get;set;} 
    public String account_code {get;set;} 
    public Long timestamp {get;set;} 

    public static PurchaseOrderCancel WrappedPO(Purchase_Order__c poIn){
        PurchaseOrderCancel poWrapped = new PurchaseOrderCancel();
        
        poWrapped.id = poIn.Id;
        poWrapped.external_order_number = poIn.Name;
        poWrapped.account_code = poIn.Account_Code__c;
        poWrapped.cancellation_reason = poIn.Cancellation_Reason__c;
        
        if(poIn.LastModifiedDate != null){
            poWrapped.timestamp = poIn.LastModifiedDate.getTime();
        }
        
        if(poIn.createdDate != null){
            poWrapped.timestamp = poIn.createdDate.getTime();
        }
        
        if(poWrapped.timestamp == null)
        {
            poWrapped.timestamp = System.now().getTime();
        }
        return poWrapped;
    }
}