force-app/main/default/objects/ServiceAppointment/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <description>The case number is used to send the service report using a trigger</description>
    <formula>Work_Order__r.Case.CaseNumber</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Site_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Site_Contact_Email__c</fullName>
    <description>This email is used to send the service report using a trigger</description>
    <formula>Work_Order__r.Site_Contact__r.Email</formula>
    <label>Site Contact Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Site_Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Site_Contact_ID__c</fullName>
    <formula>Work_Order__r.Site_Contact__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site_Contact_ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ServiceAppointmentDAO.cls
public class ServiceAppointmentDAO {

    public static  List<ServiceAppointment> getServiceAppointments(Set<id> saIds){
        List<ServiceAppointment> serviceAppointments = [SELECT id, 
                                                               Site_Contact_Email__c, 
                                                               Case_Number__c, 
                                                               Site_Contact_ID__c,
                                                               ParentRecordId
                                                        FROM   ServiceAppointment 
                                                        WHERE id 
                                                        IN :saIds 
                                                        AND Site_Contact_Email__c <>NULL];

        return serviceAppointments;
        
    }
    
    public static  List<ServiceAppointment> getOpenServiceAppointments(Set<id> woIds){
        List<ServiceAppointment> serviceAppointments = [SELECT id, 
                                                               AppointmentNumber, 
                                                               Status,
                                                               ParentRecordId
                                                        FROM   ServiceAppointment 
                                                        WHERE ParentRecordId 
                                                        IN :woIds 
                                                        AND Status <> :Constants.SERVICE_APPOINMENT_STATUS_COMPLETE
                                                        AND Status <> :Constants.SERVICE_APPOINMENT_STATUS_CANNOT_COMPLETE];

        return serviceAppointments;
        
    }
}