force-app/main/default/objects/Aggregate_Billing_Format__mdt/Aggregate_Billing_Format__mdt.object-meta.xml
<CustomObject>
    <label>Aggregate Billing Format</label>
    <pluralLabel>Aggregate Billing Format</pluralLabel>
</CustomObject>

force-app/main/default/objects/Aggregate_Billing_Format__mdt/fields/WO_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>WO_Field_Name__c</fullName>
    <label>WO Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <description>This object will be used to create records for the purpose of invoicing</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <defaultValue>&quot;AUD&quot;</defaultValue>
    <label>Currency</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/recordTypes/AggregatedBilling_SalesOrder_RT.recordType-meta.xml
<RecordType>
    <fullName>AggregatedBilling_SalesOrder_RT</fullName>
    <active>true</active>
    <label>Aggregated Billing</label>
</RecordType>

force-app/main/default/objects/Sales_Order_Line_Item__c/Sales_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{000000}</displayFormat>
        <label>Sales Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Indicates what this sales items is about</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Item_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Code__c</fullName>
    <label>Item Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Note</fullName>
            </value>
            <value>
                <fullName>Special (S)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Item_Price__c.field-meta.xml
<CustomField>
    <fullName>Item_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Indicates the price of this item</description>
    <label>Item Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Order_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Order_Quantity__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Order Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <description>Parent Sales Order</description>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipName>Sales_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <defaultValue>10.0</defaultValue>
    <label>Tax Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <description>Unit of measure</description>
    <label>Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Units</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Aggregate_Billing_Format__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Billing_Format__c</fullName>
    <label>Aggregate Billing Format</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Service Contracts</relationshipLabel>
    <relationshipName>Service_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Customer_Purchase_Order_number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Purchase_Order_number__c</fullName>
    <label>Customer Reference</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Materials_Total__c.field-meta.xml
<CustomField>
    <fullName>Materials_Total__c</fullName>
    <label>Materials Total</label>
    <summarizedField>WorkOrderLineItem.TECH_Total_ex_GST__c</summarizedField>
    <summaryFilterItems>
        <field>WorkOrderLineItem.StartDate</field>
        <operation>equals</operation>
        <value/>
    </summaryFilterItems>
    <summaryForeignKey>WorkOrderLineItem.WorkOrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Total_Billable_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Billable_Hours__c</fullName>
    <label>Total Billable Hours</label>
    <summarizedField>WorkOrderLineItem.Billable_Hours__c</summarizedField>
    <summaryForeignKey>WorkOrderLineItem.WorkOrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Use_Pre_purchased_Hours__c.field-meta.xml
<CustomField>
    <fullName>Use_Pre_purchased_Hours__c</fullName>
    <label>Use Pre purchased Hours</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Units.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EACH</fullName>
        <label>Each</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>PACK OF 10</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
    </customValue>
    <customValue>
        <fullName>1000</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <label>Pack of 200</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>Pack of 25</label>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>500</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
        <label>Bag</label>
    </customValue>
    <customValue>
        <fullName>BOX</fullName>
        <label>1 Box</label>
    </customValue>
    <customValue>
        <fullName>BTLE</fullName>
        <label>Bottle</label>
    </customValue>
    <customValue>
        <fullName>BUCK</fullName>
        <label>Bucket</label>
    </customValue>
    <customValue>
        <fullName>CARD</fullName>
        <label>Card</label>
    </customValue>
    <customValue>
        <fullName>CART</fullName>
        <label>Cartridge</label>
    </customValue>
    <customValue>
        <fullName>COIL</fullName>
        <label>Coil</label>
    </customValue>
    <customValue>
        <fullName>COUT</fullName>
        <label>Callout</label>
    </customValue>
    <customValue>
        <fullName>CTN</fullName>
        <label>Carton</label>
    </customValue>
    <customValue>
        <fullName>DAY</fullName>
        <label>Day</label>
    </customValue>
    <customValue>
        <fullName>DRUM</fullName>
        <label>Drum</label>
    </customValue>
    <customValue>
        <fullName>HOUR</fullName>
        <label>Hour</label>
    </customValue>
    <customValue>
        <fullName>HRS</fullName>
        <label>Hours</label>
    </customValue>
    <customValue>
        <fullName>JAR</fullName>
        <label>Jar</label>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
        <label>Kilogram</label>
    </customValue>
    <customValue>
        <fullName>KIT</fullName>
        <label>Kit</label>
    </customValue>
    <customValue>
        <fullName>KM</fullName>
        <label>Kilometre</label>
    </customValue>
    <customValue>
        <fullName>LEN</fullName>
        <label>Length</label>
    </customValue>
    <customValue>
        <fullName>LOT</fullName>
        <label>Lot</label>
    </customValue>
    <customValue>
        <fullName>LTR</fullName>
        <label>Litre</label>
    </customValue>
    <customValue>
        <fullName>MM</fullName>
        <label>Millimetre</label>
    </customValue>
    <masterLabel>Units</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AggregateBillingFormatController.cls
public with sharing class AggregateBillingFormatController {
    @AuraEnabled(cacheable=true)
    public static Map<String,Aggregate_Billing_Format__mdt> getBillingFormatsMap(){
        Map<String,Aggregate_Billing_Format__mdt> billingFormats = new Map<String,Aggregate_Billing_Format__mdt>();
        List<Aggregate_Billing_Format__mdt> formats = [Select MasterLabel,WO_Field_Name__c  From Aggregate_Billing_Format__mdt];
        for(Aggregate_Billing_Format__mdt abf : formats){
            billingFormats.put(abf.WO_Field_Name__c, abf);
        }
        return billingFormats;
    }
    
    @AuraEnabled(cacheable=true)
    public static Map<String,Aggregate_Billing_Format__mdt> getBillingFormatsMapByMasterLabel(){
        Map<String,Aggregate_Billing_Format__mdt> billingFormats = new Map<String,Aggregate_Billing_Format__mdt>();
        List<Aggregate_Billing_Format__mdt> formats = [Select MasterLabel,WO_Field_Name__c  From Aggregate_Billing_Format__mdt];
        for(Aggregate_Billing_Format__mdt abf : formats){
            billingFormats.put(abf.MasterLabel, abf);
        }
        return billingFormats;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getBillingFormats(){
        List<Aggregate_Billing_Format__mdt> formats = [Select MasterLabel,WO_Field_Name__c  From Aggregate_Billing_Format__mdt];
        List<String> bFormats = new List<String>();
		for(Aggregate_Billing_Format__mdt abf : formats){
            bFormats.add(abf.MasterLabel);
        }        
        return bFormats;
    }
    
    @AuraEnabled
    public static ServiceContract saveServiceContract(ServiceContract contract,String billingFormat){
        System.debug('****billingFormat:'+billingFormat);
        List<BillingFormat> billingFormatList = (List<BillingFormat>)JSON.deserialize(billingFormat, List<BillingFormat>.class);
        Map<String,Aggregate_Billing_Format__mdt> formatMDT = getBillingFormatsMapByMasterLabel();
        String aggFormat = '';
        for(BillingFormat bFormat : billingFormatList){
            aggFormat += formatMDT.get(bFormat.value).WO_Field_Name__c+':'+bFormat.label+',';
        }
        contract.Aggregate_Billing_Format__c = aggFormat;
        upsert contract;
        return contract;
    }
    
    @AuraEnabled(cacheable=true)
    public static ServiceContract getServiceContract(Id contractId){
        List<ServiceContract> formats = [Select  Id,
                                                 Name,
                                                 Aggregate_Billing_Format__c,
                                                 Service_Territory__c,
                                                 AccountId
                                         From 	 ServiceContract Where Id = :contractId];
        return formats.get(0);
    }
    
    @AuraEnabled(cacheable=true)
    public static List<BillingFormat> getServiceContractBillingFormat(Id contractId){
        List<BillingFormat> bFormats = new List<BillingFormat>();
        List<ServiceContract> formats = [Select Id,Name,Aggregate_Billing_Format__c From ServiceContract Where Id = :contractId];
        Map<String,Aggregate_Billing_Format__mdt> formatMDT = getBillingFormatsMap();
        if(formats.size() > 0 && formats.get(0).Aggregate_Billing_Format__c != null){
            for(String fieldFormat : formats.get(0).Aggregate_Billing_Format__c.split(',')){
                List<String> ff = fieldFormat.split(':');
                String masterLabel = ff.size() > 0 ? formatMDT.get(ff.get(0)).MasterLabel : '';
                BillingFormat bf = new BillingFormat(masterLabel,(ff.size() > 1 ? ff.get(1) : ''));
                bFormats.add(bf);            
            }
        }
        System.debug(bFormats);
        return bFormats;
    }
    
    @AuraEnabled
    public static List<WorkOrder> getWorkOrderForContractWithStatus(Id contractId, String workOrderStatus){
        List<WorkOrder> wos = [SELECT id, 
                                             ServiceContractId, 
                                             ServiceContract.Name, 
                                             Use_Pre_purchased_Hours__c,
                                             Customer_Purchase_Order_number__c,
                                             WorkOrderNumber,
                                             Subject,
                                             Total_Billable_Hours__c,
                                             Materials_Total__c,
                                             Subtotal    
                                      FROM   WorkOrder 
                                      WHERE  ServiceContractId = :contractId
                              		  AND	 Status = :workOrderStatus
                              		  AND 	 Sales_Order__c = null];

        return wos;
    }
    
    @AuraEnabled
    public static Id createSalesOrder(ServiceContract contract,String workOrderIds){
        Sales_Order__c sOrder = null;
        
        String aggregateRecordTypeId = Schema.SObjectType.Sales_Order__c.getRecordTypeInfosByDeveloperName ().get('AggregatedBilling_SalesOrder_RT').getRecordTypeId();
        
        System.debug('****workOrderIds:'+workOrderIds);
        Set<Id> woIds = (Set<Id>)JSON.deserialize(workOrderIds, Set<Id>.class);
        System.debug('****woIds:'+woIds.size())    ; 
        
        try{
            if(woIds.size() > 0){
                List<WorkOrder> wOrders = WorkOrderDAO.getWorkOrdersUsingIds(woIds);
                sOrder = new Sales_Order__c(Account__c = contract.AccountId ,
                                                          Currency__c = 'AUD',
                                                          RecordTypeId = aggregateRecordTypeId,
                                                          Service_Contract__c = contract.Id,
                                                          Service_Territory__c = contract.Service_Territory__c,
                                                          Order_Date__c = System.today() );
                insert sOrder;
                System.debug('***sOrder:'+sOrder);
                List<Sales_Order_Line_Item__c> solItems = new List<Sales_Order_Line_Item__c>();
                for(WorkOrder wOrder : wOrders){
                    solItems.add(new Sales_Order_Line_Item__c(Work_Order__c = wOrder.Id,
                                                              Sales_Order__c   = sOrder.Id,
                                                              Description__c = wOrder.Subject,
                                                              Item_Code__c = 'Special (S)',
                                                              Order_Quantity__c = 1,
                                                              Tax_Rate__c = 10,
                                                              Units__c = 'EACH',
                                                              Item_Price__c = wOrder.Subtotal));
                    wOrder.Sales_Order__c = sOrder.Id;
                }
                System.debug('***solItems:'+solItems);
                if(solItems.size() > 0){
                    insert solItems;
                }
                update wOrders;
                
            }
        }catch(Exception ex){
            throw new AuraHandledException(ex.getMessage());  
        }
        return sOrder != null ? sOrder.Id : null;
    }
    
    public class BillingFormat{
        @AuraEnabled
        public String value {get; set;}
        @AuraEnabled
        public String label {get; set;}   
        
        public BillingFormat(String value, String label){
            this.value = value;
            this.label = label;
        }
        
       public BillingFormat(){
            this.value = '';
            this.label = '';            
        }
        
        public BillingFormat parse(String json) {
            return (BillingFormat) System.JSON.deserialize(json, BillingFormat.class);
        }
    }
    	
}